### ISSUE TITLE
OneNote section groups not importing properly

### ISSUE THREAD

**Issue by teecrow** [obsidianmd/obsidian-importer#100]
Rather than organizing my notes by [notebook] --> [sections], I have most sections organized under section _groups_, such that my OneNote is organized as [notebook] --> [section group] --> [sections]. Sections are nested in section groups which are nested within notebooks.

In the Importer, the _sections_ at the top level of my notebook import correctly, but the _section groups_ simply don't appear on the list. Any plans to change this? Section groups exported for me without issue when I used the tool at https://github.com/theohbrothers/ConvertOneNote2MarkDown

Looking forward to getting many of my notes into Obsidian! Thanks for all the great work.

**Comment by DeanAmiridis** [comment]
I just realized this when trying to use the importer as well. I don't see my section groups and anything nested within it at all. 

Hope this is something we can accomplish at some point, this way I can finally divorce from OneNote (mostly used for work).

**Comment by p3rid0t** [comment]
Should be fixed in the next release of the Importer! It didn't work because of a little typo in an URL :p

**Comment by DeanAmiridis** [comment]
> Should be fixed in the next release of the Importer! It didn't work because of a little typo in an URL :p

Thank you so much for the quick-fix! Looking forward to it; Appreciate your hard work.
