### ISSUE TITLE
[OneNote] Saving images uses too coarse naming scheme

### ISSUE THREAD

**Issue by ashemedai** [obsidianmd/obsidian-importer#102]
When using the Importer for OneNote I was greeted with 1600+ failures reported.

Upon investigating I think the [granularity used for saving images](https://github.com/obsidianmd/obsidian-importer/blob/master/src/formats/onenote.ts#L363-L367) is too coarse:

```
Failed: "Exported image 20230912081953.png" because Error: File already exists.
Failed: "Exported image 20230912081953.png" because Error: File already exists.
Failed: "Exported image 20230912081953.png" because Error: File already exists.
Failed: "Exported image 20230912081953.png" because Error: File already exists.
Failed: "Exported image 20230912081953.png" because Error: File already exists.
Failed: "Exported image 20230912081953.png" because Error: File already exists.
Failed: "Exported image 20230912081953.png" because Error: File already exists.
```

One possible, easy fix could be to have a simple increasing variable in that loop to add an additional unique identifier to the filename so that you get something like (semi-pseudocode):

```ts
iterator += 1
const currentDate = moment().format('YYYYMMDDHHmmss');
const fileName: string = `Exported image ${currentDate}${iterator}.${extension}`;
```

Another approach is to replace the datetimestamp approach and use UUIDv4 for the naming to guarantee uniqueness.

**Comment by ashemedai** [comment]
@p3rid0t @tgrosinger What do you think?

**Comment by vladik-pwnz** [comment]
the problem has not been solved - everything also crashes because of the same names
