### ISSUE TITLE
OneNote bug squash bounty — $300

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#105]
## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $300 USD
**Timeframe:** 10 days

## Requirements

Similar to #84 but for OneNote 

- [x] #100 
- [x] #95 
- [x] #102
- [x] #103
- [x] #94

**Comment by kepano** [comment]
Assigning to @p3rid0t

**Comment by p3rid0t** [comment]
I accept this bounty since I have developed the OneNote Importer before. Thank you!

**Comment by jbins6499** [comment]
> 

You are a saint. Very excited to finally have a good pipeline from OneNote to Obsidian. Let me know if there's anything someone like me can do to help test etc. I'm @jaybins in the discord

**Comment by ericaxu** [comment]
> > 
> 
> You are a saint. Very excited to finally have a good pipeline from OneNote to Obsidian. Let me know if there's anything someone like me can do to help test etc. I'm jaybins in the discord

Be sure to join the #importer thread on Discord! Most of the testing opportunities will be posted and done there.
