### ISSUE TITLE
Importer gets OneNote section names but does not import the notes

### ISSUE THREAD

**Issue by psterpe** [obsidianmd/obsidian-importer#109]
Running Obsidian 1.4.13 on macOS Ventura 13.2.1 using v1.3.1 of the Importer. My machine is a MacBook Pro with Apple M1 chip.
In the Importer:

* Select _Microsoft OneNote_ from the File format dropdown
* Enter "OneNote" for the Output folder
* Leave _Use the default attachment folder_ in the On state
* Leave _Import incompatible attachments_ in the Off state
* Click the _Sign in_ button to sign into Microsoft account. This opens a new browser tab (I'm using Edge) that displays "Are you trying to sign in to Obsidian Importer?" along with Cancel and Continue buttons.
* Click Continue. Focus returns to Obsidian Importer where Obsidian briefly displays "Unexpected auth event. Please restart the auth process."

This much was reported in [issue 93](https://github.com/obsidianmd/obsidian-importer/issues/93). I find that the importer does display, beneath _Choose data to import_, a list of my notebooks with a checkbox next to each section name.

* Click any section name(s) to indicate that you want to import it(them).
* Click the _Import_ button.

The _Import data into Obsidian_ dialog displays "Starting OneNote import...". This message remains regardless of how long you wait. Above the various category labels (imported, attachments, remaining, skipped, failed), all have a 0 except _remaining_ which counts down to 1 if you selected more than one section to import. The Done button lights up to be clickable.

* Click the _Done_ button. The dialog disappears. In Obsidian, you will see expandable headings corresponding to the notebook sections you chose to import, but there are no notes beneath any heading. Occasionally, one note from one section does import successfully, although there are 17 other notes in that section which do not import.

**Comment by kepano** [comment]
Are you seeing any console errors?

**Comment by liamlah** [comment]
I've just tried importing, (Windows 11)

I get the *exact* same behaviour (same process followed)
I checked the console, I don't 100% know what I should be looking for, however:

on the line that I get "plugin:obsidian-importer"
it shows  "Current progress: 0.0%" even after the done button has appeared clickable, and the section names have been imported. I can't see anything else that looks like an error.

**Comment by psterpe** [comment]
Sorry for the lag in responding. I hadn't thought to check for console
errors. I tried the import again, this time with the developer console in
view. This is all I saw in the console:

**Comment by psterpe** [comment]
Ah, and I did also see that "Current progress: 0.0%" message (in the
console) that Liam reported. It appeared to have been issued 3 times (I
tried to import 3 sections).

**Comment by ThinkDualBrain** [comment]
I'm having the same problem, but my console is littered with 429 errors. Looks related to another problem with rate limiting? #120, but I'm not getting the content with error messages like @voltagex

**Comment by legolasdimir** [comment]
I am seeing the same results. blank folders get created but no notes are added in most sections and notebooks. There are some where it will import like.. the top page and that's it. no console errors.

**Comment by Triorama** [comment]
Same Problem here. Using Version 1.5.2 on a MacBook Air M2 running Sonoma 14.0 and obsidian 1.4.16

**Comment by bellicose100xp** [comment]
Same problem, All the section folders are imported but no actual content in those folders. I'm on Windows 10, Obsidian version 1.4.16.

**Comment by Joeysantoro** [comment]
Same Issue, I tried downloading my .one zip files and reuploading to a fresh onenote account and still get this behavior. M2 Macbook using most up to date importer

**Comment by adamhill** [comment]
I am getting a variation of the above:

- All of the _Pages_ get imported, flat into the root, but no sections containing those pages
- The exact same images get imported in each page
-  No text from the page gets pulled in

My notebook is 100% non-sensitive, if you need it to help repro the problem

**Comment by el-rocho** [comment]
Same problem, All the section folders are imported but no actual content in those folders. I'm on Windows 11, Obsidian version 1.4.16.

**Comment by abr05** [comment]
Same problem. See the following log: 
Sonoma 14.3 Macbook Air M1 
Importer v 1.5.6
Obsidian v 1.5.3
Followed same steps as outlined in opening comment on this 


```
app.js:1 Obsidian Developer Console
app.js:1 Received URL action Object
graph.microsoft.com/v1.0/me/onenote/notebooks[...]    Failed to load resource: the server responded with a status of 429 ()
plugin:obsidian-importer:212 Uncaught (in promise) TypeError: o is not iterable
    at Fr.showSectionPickerUI (plugin:obsidian-importer:212:1428)
app.js:1 Received URL action Object
app.js:1 Received URL action Object
app.js:1 Received URL action Object
app.js:1 Received URL action Object
graph.microsoft.com/v1.0/me/onenote/notebooks?[...]   Failed to load resource: the server responded with a status of 429 ()
plugin:obsidian-importer:212 Uncaught (in promise) TypeError: o is not iterable
    at Fr.showSectionPickerUI (plugin:obsidian-importer:212:1428)
app.js:1 Received URL action Object
app.js:1 Received URL action {code: 'M.C104_SN1.2.a0c682ec-8f73-3c2c-ab43-42b7a83f563a', state: 'f02961fb9bbada149bcc24828b8ceb86', action: 'importer-auth'}
plugin:obsidian-importer:216     GET https://graph.microsoft.com/v1.0/me/onenote/notebooks?[...]orderby=createdDateTime 429
fetchResource @ plugin:obsidian-importer:216
showSectionPickerUI @ plugin:obsidian-importer:212
authenticateUser @ plugin:obsidian-importer:212
await in authenticateUser (async)
eval @ plugin:obsidian-importer:221
t @ app.js:1
(anonymous) @ VM241:1
(anonymous) @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2
plugin:obsidian-importer:212 Uncaught (in promise) TypeError: o is not iterable
    at Fr.showSectionPickerUI (plugin:obsidian-importer:212:1428)
showSectionPickerUI @ plugin:obsidian-importer:212
await in showSectionPickerUI (async)
authenticateUser @ plugin:obsidian-importer:212
await in authenticateUser (async)
eval @ plugin:obsidian-importer:221
t @ app.js:1
(anonymous) @ VM241:1
(anonymous) @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
emit @ node:events:513
onMessage @ node:electron/js2c/renderer_init:2

```

**Comment by tgrosinger** [comment]
This should be resolved in the latest release - https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.1
