### ISSUE TITLE
Notion Import: Naming error when note has a slash in the title

### ISSUE THREAD

**Issue by jericjan** [obsidianmd/obsidian-importer#110]
I noticed that if I import a note that has a slash in the title in Notion, the slash gets removed in the folder name and corresponding note name, but if I link to any files inside the note, it will remove the slash and if there are adjacent spaces, it will reduce it to a single space.

This is an example export where a note is titled "test / note"
[Notion-export-test.zip](https://github.com/obsidianmd/obsidian-importer/files/12642147/Notion-export-test.zip)

The folder name and note name becomes "test[SPACE][SPACE]note", while links in the note become "test[SPACE]note"

If the note was titled "test/note" in Notion, there are no issues whatsoever.

The same happens for backslashes as well:

If I title it `test             \ note` in Notion, the folder and note title in Obsidian becomes `test              note`, while the link becomes `test note`

# Proposed Solution:
Maybe replace the slashes with a keyword like "OR". Else it's going to be confusing to read some of these titles when the slashes suddenly disappear. There would need to be an exception for dates like `MM/DD/YY` though. In that case, it should be a dash instead.

**Comment by joshuatazrein** [comment]
I agree slashes should be replaced. I think I'll use the dash since it's the most unobtrusive. OR might get confusing for people.

**Comment by kepano** [comment]
Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)
