### ISSUE TITLE
Notion: spaced tags get turned into separate tags

### ISSUE THREAD

**Issue by jericjan** [obsidianmd/obsidian-importer#111]
Here is a sample in Notion:
![image](https://github.com/obsidianmd/obsidian-importer/assets/38642145/e76743b3-6f5f-4ee9-b722-147799ff3f2e)

After uploading to Obsidian, the tags get separated:
![image](https://github.com/obsidianmd/obsidian-importer/assets/38642145/77267dfa-effe-4f05-aca7-fc4fffc6469d)

It would be great if the spaces were replaced with dashes. Thanks in advanced!

Here is the sample exported:
[spaced-tag.zip](https://github.com/obsidianmd/obsidian-importer/files/12642241/spaced-tag.zip)

**Comment by kepano** [comment]
Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)
