### ISSUE TITLE
Notion: Bookmark conversion issue for "youtu.be" links.

### ISSUE THREAD

**Issue by Satanniel** [obsidianmd/obsidian-importer#112]
So the importer converts bookmarks (link with some embed information) to callouts since there is no corresponding native option in Obsidian.
But for bookmarks for youtu.be (youtube.com appears to work fine) it insert complete video description.

I'm attaching an example HTML file exported from notion and the resultant MD file.
[youtube embed example.zip](https://github.com/obsidianmd/obsidian-importer/files/12643452/youtube.embed.example.zip)

**Comment by joshuatazrein** [comment]
In the upcoming update Importer will only include the first sentence for embed descriptions.

**Comment by kepano** [comment]
Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)
