### ISSUE TITLE
Importing a lot of pdf files from onenote

### ISSUE THREAD

**Issue by chairman2s** [obsidianmd/obsidian-importer#113]
Hi

I set up my scanner many years ago to save all the documents into OneNote. It looked like a good idea then... 

Now I want to import everything into Obsidian. The documents that were scanned are saved as PDF files inside OneNote. When I try to import the notebook into Obsidian it works almost. But a lot of the pdf files get broken. So I opened the broken PDF files in Notepad and there I found this message:

/
`{"error":{"code":"20166","message":"The app has issued too many requests on behalf of this user in a short time period.","innerError":{"date":"2023-09-20T07:38:24","request-id":"557db4ee-47ea-4047-80e1-7a7cfb9b43e7","client-request-id":"557db4ee-47ea-4047-80e1-7a7cfb9b43e7"}}}`

So maybe there should be a throttling control or something

**Comment by p3rid0t** [comment]
Thanks for submitting an issue, this should be fixed in the next Importer version 😺
