### ISSUE TITLE
Notion: The URL of the image is incorrect

### ISSUE THREAD

**Issue by madroidmaq** [obsidianmd/obsidian-importer#114]
Image cannot be positioned correctly

notion zip file
<img width="652" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/6247142/2279b379-2274-48cd-97eb-44d33ae61187">

Directory information after import:
<img width="349" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/6247142/7540553a-1daa-4f32-895c-5890ad82d95e">

Image information of the imported file:
<img width="741" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/6247142/1287fd6f-6511-4e62-8d8e-2f218505bc59">

It can be seen that the path of the picture folder is inconsistent with the path of the picture.

**Comment by joshuatazrein** [comment]
Does it still link to the image? `%20` just means space, so the URL should still work.

**Comment by madroidmaq** [comment]
@joshuatazrein it cannt link to the image, because the file where the image is placed no longer contains information similar to uuid, it is just a demo。
<img width="697" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/6247142/1cf714a1-f6a2-45e2-9f5c-b595da01c55a">

**Comment by joshuatazrein** [comment]
Can you upload this demo file here as a zip? I'll debug.

**Comment by madroidmaq** [comment]
@joshuatazrein The following are the corresponding attachments:

[53e0912f-0d0a-4237-8947-93cf295b1ee1_Export-cbcfaaed-92c0-4779-a174-4447f618c50a.zip](https://github.com/obsidianmd/obsidian-importer/files/12803485/53e0912f-0d0a-4237-8947-93cf295b1ee1_Export-cbcfaaed-92c0-4779-a174-4447f618c50a.zip)

Here's how I do my export:
<img width="302" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/6247142/3d406683-3b5e-437c-8e1a-3bf83c802f13">
<img width="330" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/6247142/3d83136e-30ff-4862-a121-12e0ab0b185b">

**Comment by joshuatazrein** [comment]
Thanks

**Comment by madroidmaq** [comment]
> Thanks—sorry, I also need the export from Notion.

You can directly download the zip file that I have exported, I have given the download link in my last comment。

[53e0912f-0d0a-4237-8947-93cf295b1ee1_Export-cbcfaaed-92c0-4779-a174-4447f618c50a.zip](https://github.com/obsidianmd/obsidian-importer/files/12803485/53e0912f-0d0a-4237-8947-93cf295b1ee1_Export-cbcfaaed-92c0-4779-a174-4447f618c50a.zip)

**Comment by joshuatazrein** [comment]
Ah, I see what the issue is. You used the "Markdown" export option from Notion, but it should be the "HTML" export. I will add an error letting people know about this to provide more guidelines.
