### ISSUE TITLE
Deprecate 'Format Importer' core plugin

### ISSUE THREAD

**Issue by p3rid0t** [obsidianmd/obsidian-importer#115]
With this new open source (💜) plugin, the older Format Converter plugin no longer makes sense as a separate option.
The older plugin may only confuse some users, as they both have very similar names. As a little side bonus, the Obsidian codebase might get a bit cleaner :)

To solve this, we can either:
- add Markdown as a supported format in this new plugin,
- or remove the format option altogether (AFAIK, it only converted some links and images?) - not sure how often it was used

**Comment by kepano** [comment]
Agreed, see #23

**Comment by kepano** [comment]
Closing since this will be solved in Obsidian core after #23 is completed
