### ISSUE TITLE
Import from Google Keep - $500

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#12]
Please upvote this issue if you would like to see Google Keep as an import format.

## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $500 USD
**Timeframe:** 10 days

## Requirements

By using the existing HTML importer you should be to convert Google Keep's HTML export

- [ ] Must work on macOS, Windows, Linux
- [ ] Convert to proper Obsidian Markdown formatting
- [ ] Maintain folder structure
- [ ] Apply the created/modified date to the created Markdown file
- [ ] Follow the user's setting for `Default location for new attachments`
- [ ] Use Obsidian-style embed links for attachments `![[image.png]]`

## Current solutions

- [See Obsidian forum](https://forum.obsidian.md/t/google-keep-notes-to-obsidian-markdown-python-converter/12714)
- [obsidian_google-keep-import](https://github.com/daledesilva/obsidian_google-keep-import)

**Comment by dbarenholz** [comment]
This (apparently) exists: https://github.com/daledesilva/obsidian_google-keep-import

**Comment by daledesilva** [comment]
Hi!
I would like to apply for this bounty.
I am the developer of the [Google Keep Import community plugin](https://github.com/daledesilva/obsidian_google-keep-import) and so I am already familiar with format and the requirements.

In maintaining that plug-in, I have also been able to learn about different users setups and expectations in importing their keep notes that would allow me to more efficiently rewrite it for core inclusion.

**Comment by kepano** [comment]
@daledesilva ok! You're assigned! Let us know in the Discord channel if you have any questions 😊

**Comment by kepano** [comment]
Please make sure to submit your PR by end of day (GMT) on August 4th, 2023. Thanks!

**Comment by daledesilva** [comment]
I've submitted my PR [here](https://github.com/obsidianmd/obsidian-importer/pull/37), but noted that I didn't meet the requirement of following the users default location for new attachments.

I was going to fix it, but I'd like to question it. I don't think this is the best approach.

Importing from Google Keep is a one time operation, so if the files land in an different assets folder, it is really just a quick drag and drop for them to move it where they would like, or to delete them if the import didn't meet their expectations somehow.

On the flipside, if the attachments go into their default attachment location, and the import doesn't meet their expectations, all the Keep attachments will now be dispersed amongst their normal attachments and it will be very hard for them to remove - they would have to somehow identify each file and select them one at a time.

My suggestion is that we leave it as is and if they want to move the files they can do it after confirming the import went well.

**Comment by daledesilva** [comment]
I think that's actually degrading the experience slightly.

It means more options for the user before import, whereas we can very safely just import it all and if they wanna rename the folder later once they see how it works they can without problem.

**Comment by daledesilva** [comment]
Options before would make sense if this was an action they do periodically, as it would save them having to rename each time (if we remembered their options).

But I think this is really a one time operation for users.

**Comment by daledesilva** [comment]
Oh, I think I misunderstood what you said slightly.

We could move the folder...

From this (currently):
`Google Keep/Assets`

To:
`default import folder/Keep Assets/`

Happy to do it if you want, but I think it's better as is. Currently it keeps all the imported stuff together for easy one click deletion if anything goes wrong. And they can easily move the folder or files if they're happy with it.

I agree with the sentiment of staying consistent with user preferences, but I think one time imports from another program are special use cases that have different needs and expectations from the user.

**Comment by daledesilva** [comment]
As a counter point, what I describe above probably works differently from the other importer formats, so that's important to consider too.

Happy to do whatever, will wait for the final call.
