### ISSUE TITLE
Import from Evernote

### ISSUE THREAD

**Issue by sploo1012** [obsidianmd/obsidian-importer#123]
With files imported from Evernote, I find that some notes have a message that says that the ".pdf has not been created yet". When I click the message, it creates a new note with the name of the .pdf but no file.

**Comment by ericaxu** [comment]
Please make your issue title more descriptive, thanks!

**Comment by sploo1012** [comment]
Thank you for the correction! I'm not seeing any examples of this happening now in my Vault so perhaps it was a sync error? I'll close this bug report.
