### ISSUE TITLE
[OneNote] Does not discover nested section groups

### ISSUE THREAD

**Issue by hakenr** [obsidianmd/obsidian-importer#130]
OneNote:
![image](https://github.com/obsidianmd/obsidian-importer/assets/12828888/cc82f318-ecf6-45bf-a4c4-af5eacd7b9df)

Importer:
![image](https://github.com/obsidianmd/obsidian-importer/assets/12828888/55a9b0d2-34c5-465d-8dfb-168ab802dcda)

**Comment by kepano** [comment]
Duplicate of #162
