### ISSUE TITLE
I wish Obsidian creates ChatGPT JSON support. I tried Google Keep or Roam Research JSON & zip too, but both gave an error. I am not a coder; it might be too much to ask, but Thank you so much for Notion and all the imports.

### ISSUE THREAD

**Issue by paranjay245** [obsidianmd/obsidian-importer#131]
I wish Obsidian creates ChatGPT JSON support. I tried Google Keep or Roam Research JSON & zip too, but both gave an error. I am not a coder; it might be too much to ask, but Thank you so much for Notion and all the imports.  

Edit: A clarification: What I am talking about is, for example, we can export conversations from a ChatGPT account. I wish there could be a workaround or tools available with Obsidian or online. I am searching for tools for the same purpose.

- Found out new thing it got HTML too unable to export it too

So Sorry For Alot Chaos and Obscure Issue i wasnt aware about it 

- I found a better one or i dont know anything better then it existing https://github.com/pionxzh/chatgpt-exporter

**Comment by paranjay245** [comment]
[Seeking Help to Automate ChatGPT Data Export and Import to Obsidian : ObsidianMD](https://www.reddit.com/r/ObsidianMD/comments/14vbfdc/seeking_help_to_automate_chatgpt_data_export_and/) also i found here a guy created python script or stuff idk but i dont know how to use it in reddit

Curious to know if you found an automation solution. I have so many ChatGPT conversations that manually exporting them is a pain. An automated solution would be amazing. I am still looking and can't quite find anything.



Reply
Share


User avatar
level 2
[realpivot](https://www.reddit.com/user/realpivot/)
OP
·
[3 mo. ago](https://www.reddit.com/r/ObsidianMD/comments/14vbfdc/comment/jtdmwjj/?utm_source=reddit&utm_medium=web2x&context=3)
Not really, I feel like one would have to be built but I don't have the skills lol. Seems pretty straight forward of a process. I use code interpreter to reformat my exported chats and just copy and paste. It's not ideal but it's somethign


1


Reply
Share


User avatar
level 3
[6849](https://www.reddit.com/user/6849/)
·
[3 mo. ago](https://www.reddit.com/r/ObsidianMD/comments/14vbfdc/comment/jtuqhcc/?utm_source=reddit&utm_medium=web2x&context=3)
Yea, I ended up using Code Interpreter to build a script that would automate parsing conversations.json (from an OpenAI export). In Obsidian I have a "ChatGPT" folder and I place this script there along with OpenAI's exported zip file. I run the script. Sorts every chat by date of last conversation and makes a separate folder called "Code" with ALLLLLLL of the code it ever made me.

I just pasted it to Pastebin if interested: https://pastebin.com/94vwgnvp

Perhaps one day there will be an API we can use to sync conversations. I'd love to pull them on a schedule into Obsidian without doing it manually.


1


Reply
Share


level 4
[Witty-Mistake4590](https://www.reddit.com/user/Witty-Mistake4590/)
·
[just now](https://www.reddit.com/r/ObsidianMD/comments/14vbfdc/comment/k4t4hol/?utm_source=reddit&utm_medium=web2x&context=3)
hey can you help me run or give me documentation to do same


1


Reply
Share


User avatar
level 4
[realpivot](https://www.reddit.com/user/realpivot/)
OP
·
[2 mo. ago](https://www.reddit.com/r/ObsidianMD/comments/14vbfdc/comment/ju8eqve/?utm_source=reddit&utm_medium=web2x&context=3)
Thank you so much I appreciate it

**Comment by kepano** [comment]
This is a better fit for a different Obsidian plugin because Importer is focused on one time import of notes.
