### ISSUE TITLE
Import from Notion - $1,000

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#14]
Please upvote this issue if you would like to see import from Notion.

## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $1,000 USD
**Timeframe:** 10 days

## Requirements

Must support the following:

- [ ] Uses either Notion's HTML or MD export (decide which one is best)
- [ ] Convert page title to file name and remove it from the top of the file
- [ ] Maintain folder structure
- [ ] Proper Obsidian Markdown formatting
- [ ] Parse internal links
- [ ] Parse page properties, including internal links must be imported into YAML frontmatter using the correct field types
  - [ ] Text
  - [ ] Date
  - [ ] Time
  - [ ] Number
  - [ ] List
  - [ ] Checkbox

Internal link format (added in Obsidian 1.4+)

```yaml
---
link: "[[Link]]"
linklist:
  - "[[Link]]"
  - "[[Link2]]"
---
```

## Current solutions

- See [Obsidian forum](https://forum.obsidian.md/t/meta-migration-workflows/15252)

**Comment by Fevol** [comment]
I'm interested in implementing the Notion importer. I have a pretty decent understanding of how Obsidian development works (developer of the [Translate](https://www.github.com/Fevol/obsidian-translate) (_released_) and [Commentator](https://www.github.com/Fevol/obsidian-criticmarkup) (**WIP**) plugins).  

As a caveat, I do not have a lot of experience with Notion itself. I am looking into it currently, but if anyone other developer has more experience with the program and format, I'll apply for a different bounty.

**Comment by joshuatazrein** [comment]
Here is a link to a repository implementing a Notion importer which I have used to import my own notes. It reads a folder of .md exports and converts them to internal links, also converting formatting: https://github.com/joshuatazrein/obsidian-notion-import

**Comment by kepano** [comment]
> Here is a link to a repository implementing a Notion importer which I have used to import my own notes. It reads a folder of .md exports and converts them to internal links, also converting formatting: https://github.com/joshuatazrein/obsidian-notion-import

Is the repo private?

**Comment by joshuatazrein** [comment]
> > Here is a link to a repository implementing a Notion importer which I have used to import my own notes. It reads a folder of .md exports and converts them to internal links, also converting formatting: https://github.com/joshuatazrein/obsidian-notion-import
> 
> Is the repo private? Also, are you applying or sharing the code for reference?

I have made it public, and yes I am applying! Thanks very much, I was going to submit this repo as an Obsidian plugin but would be thrilled to make it part of the official importer.

**Comment by kepano** [comment]
@joshuatazrein You are assigned! Please make sure to submit your PR by end of day (GMT) on August 5th, 2023. Thanks!

**Comment by joshuatazrein** [comment]
@kepano Thanks! I'm excited to start work on it. For reference, here is [my fork of obsidian-importer](https://github.com/joshuatazrein/obsidian-importer).

**Comment by Quorafind** [comment]
@joshuatazrein seems like you haven't joined the official discord: https://discord.gg/obsidianmd . And then you can find the importer channel(it is a sub-channel) in #plugin-dev/importer

**Comment by joshuatazrein** [comment]
Sounds good, I'm in!

**Comment by joshuatazrein** [comment]
Notion Importer ready for blastoff!

**Comment by MaximilianMauroner** [comment]
@joshuatazrein Maybe I'm doing something wrong, but I tried cloning your repo and ran the build, and it seems that there is a problem with my export. Any ideas?
![image](https://github.com/obsidianmd/obsidian-importer/assets/39530837/b74d70ad-ecfd-4abf-8f9c-0af6da1aff4f)

**Comment by joshuatazrein** [comment]
> @joshuatazrein Maybe I'm doing something wrong, but I tried cloning your repo and ran the build, and it seems that there is a problem with my export. Any ideas?
> ![image](https://user-images.githubusercontent.com/39530837/257285212-b74d70ad-ecfd-4abf-8f9c-0af6da1aff4f.png)

@MaximilianMauroner This also came up in the Discord. It was an issue where newlines in properties caused the Regex to fail on table cells, and has *fingers crossed* been fixed. Try cloning the updated repo and giving it a shot.
