### ISSUE TITLE
[Apple Notes] Importing locked notes

### ISSUE THREAD

**Issue by garryknight** [obsidianmd/obsidian-importer#141]
In order to import my locked notes I had to remove the locks from all of the files. It would be great if Importer could ask if I want to ignore the locks and import them anyway.

**Comment by mirnovov** [comment]
The locked notes are encrypted so while I wouldn’t say this is impossible (perhaps the credentials could be obtained somehow) it’s probably not an easy u see taking technically..

I believe other Apple Notes decoders have been able to figure out notes with separate passwords but not necessarily ones that use the users’s credentials.

**Comment by garryknight** [comment]
> it's probably not an easy task technically..

Ok. It seemed important at the time, but looking back I seem to recall that the locked notes in my case were less than 10% of the total number of notes. I can see that it could be more important for some people, perhaps using Notes in a corporate situation.
