### ISSUE TITLE
[Apple Notes] iOS/iPadOS import supported or not? 

### ISSUE THREAD

**Issue by trainbuffer** [obsidianmd/obsidian-importer#147]
The Apple Notes import [documentation](https://help.obsidian.md/import/apple-notes) says:

> We recommend importing from Apple Notes on your macOS desktop rather than iOS.

This reads to me as it is _possible_ on iOS/iPadOS. 

But listener [Arjay](https://discord.com/channels/686053708261228577/864046194195431425/1164850539473940520) wrote in to say they see this message on iOS & iPadOS:

![image0](https://github.com/obsidianmd/obsidian-importer/assets/3751726/e9f74ca6-e1f8-400a-8c3c-d0a1e4bf9d45)

🤔

**Comment by mirnovov** [comment]
It’s not currently supported. I think the documentation is written in case this changes in the future, but it might be best to be upfront and modify it if necessary.

**Comment by villasv** [comment]
Definitely in favor of updating the docs to reflect the present, not the future

**Comment by mirnovov** [comment]
The documentation has been changed in obsidianmd/obsidian-help#605 so this issue has been resolved now.
