### ISSUE TITLE
Add option to only use single line breaks when converting

### ISSUE THREAD

**Issue by jgscherber** [obsidianmd/obsidian-importer#150]
I've only experienced this when converting from Notion.

There's an option in Obsidian to not use strict line breaks in reader view, it'd be nice if this option was also added to the importer. Without this option in the importer, there ends up being lots of extra new lines in Obsidian after a conversion that aren't needed with "Use strict line breaks" disabled 

![image](https://github.com/obsidianmd/obsidian-importer/assets/6207661/6345db6b-c0c2-40f7-898a-0451158f16d0)

**Comment by joshuatazrein** [comment]
In my upcoming pull request I've added a "single line breaks" option in the Notion importer.

**Comment by kepano** [comment]
Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)
