### ISSUE TITLE
Notion bug squash bounty - $300

### ISSUE THREAD

**Issue by ericaxu** [obsidianmd/obsidian-importer#152]
Includes these bugs:
- #83 
- #87 
- #110 
- #111 
- #112 
- #114

**Comment by joshuatazrein** [comment]
I am happy to work on these!

**Comment by joshuatazrein** [comment]
Here is the [pull request](https://github.com/obsidianmd/obsidian-importer/pull/158)!

**Comment by tgrosinger** [comment]
Merged!
