### ISSUE TITLE
[Apple Notes] Long titles truncated + omit first line

### ISSUE THREAD

**Issue by scarrillo** [obsidianmd/obsidian-importer#153]
Notes with a really long "title" get truncated with an ellipsis during the import. This combined with the option to "omit first line" means some content from the original note is lost. 

I noticed a few suspicious notes with long truncated titles but no body content. I likely pasted them into Apple Notes and they appear as long, single-line, word-wrapped, paragraphs. (not proud)

Awkward, and low priority, but Apple does permit this behavior. :)

**Comment by kepano** [comment]
Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)

**Comment by scarrillo** [comment]
> Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)

Tested - Confirmed that it fixes notes with only a "title" and no body content (improvement). However, it is missing notes that contain a long "title" and a additional body content. Please advise if you'd prefer a new ticket.

Example source:
> Let's think the unthinkable, let's do the undoable. Let us prepare to grapple with the ineffable itself, and see if we may not eff it after all.
> Douglas Adams

Importer results:
> Let's think the unthinkable, let's do the undoable. Let us prepare…
> Douglas Adams

**Comment by tgrosinger** [comment]
In the importer results, is that first line the file name or the first line of the content?

cc @mirnovov

**Comment by mirnovov** [comment]
How Apple Notes works is that it’s both - the first line of content is used as the title of the note. Note also that you can disable the option to strip the title.

**Comment by scarrillo** [comment]
I would humbly request/suggest something similar to the newline check. Where the importer duplicates the title when it is forced (max line length) to trim the title and add an ellipsis. It could be a footnote in the existing "omit" option describing the exception.

> _if it’s a minority of their notes enable the option and manually add the stripped lines._

I understand your pov here, but we may not know how many notes are affected.

Is this an acceptable loss of content/data? Maybe. Are there others? 

In the example above, I might search for the term "_ineffable_" to find the Douglas Adams quote.
_(I could search for Adams if I remembered the author.) :)_
