### ISSUE TITLE
Import from Roam - $500

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#16]
Please upvote this issue if you would like to see import from Roam

## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $500 USD
**Timeframe:** 10 days

## Requirements

- [ ] Resolve page names with allowed characters only
  - [ ] Resolve date format for daily notes, convert to the user's daily note format (`YYYY-MM-DD` by default)
- [ ] Convert outlines to bullet lists with block references
- [ ] Convert highlights and todos to Obsidian Markdown
- [ ] Support for attachments

## Current solutions

- See [Obsidian forum](https://forum.obsidian.md/t/meta-migration-workflows/15252)

**Comment by 8bitgentleman** [comment]
Hello, I have extensive experience building extensions around the Roam format and already have 13 extensions reviewed and available in the Roam extension depot (with 3 more awaiting approval).
I would like to put my name forward for this bounty, here is a link to all of my approved Roam extensions 
https://github.com/Roam-Research/roam-depot/tree/main/extensions/8bitgentleman

**Comment by kepano** [comment]
@8bitgentleman have you used Obsidian, and can you share any code related to Obsidian (e.g. community plugins) — we just want to make sure you have some familiarity with how to implement things on the Obsidian side.

**Comment by 8bitgentleman** [comment]
Hi @kepano Yes I do use Obsidian. I don't have any Obsidian plugins published to the larger community but I do have a personal one that I've just put onto github so you can take a look. It's bare bones and catered for my use case now but if I were to publish it I'd probably add more error handling and settings options for a user to customize what metadata is imported 

https://github.com/8bitgentleman/obsidian-import-book-metadata

**Comment by kepano** [comment]
@8bitgentleman You are assigned! Please make sure to submit your PR by end of day (GMT) on August 10th, 2023. Thanks!

Join the #plugin-dev/importer channel: https://discord.gg/obsidianmd
