### ISSUE TITLE
Apple Notes import stopped working after update to 14.1 (auto-vacuum problem)

### ISSUE THREAD

**Issue by LubosKolouch** [obsidianmd/obsidian-importer#160]
Hello,

After update to Sonoma 14.1 nothing gets imported and I am getting this error message.

I tested it with an empty vault to be sure.

![Screenshot 2023-10-27 at 20 19 41](https://github.com/obsidianmd/obsidian-importer/assets/4145223/3879973a-bd88-4392-b6d3-951b068b8e8f)
![Screenshot 2023-10-27 at 20 21 15](https://github.com/obsidianmd/obsidian-importer/assets/4145223/f08166df-738d-454e-8b39-bde7cf84fe71)

**Comment by mirnovov** [comment]
Works for me on 14.1. Do you have any installations of the SQLite CLI apart from the one bundled in macOS?

**Comment by LubosKolouch** [comment]
You are right, for some reason I did have a .sqliterc with the vacuum setting.

The issue can be closed, it works again, thanks.
