### ISSUE TITLE
Possible to import with titles/file names that are illegal in Obsidian

### ISSUE THREAD

**Issue by jecorn** [obsidianmd/obsidian-importer#161]
First off, thanks for the amazing work!  I just imported almost 1000 notes from Apple Notes on Sonoma with almost no problems.

But I did notice one thing. I had a few Apple Notes that contain a ‘#’ character in the title. For example, ‘My note #2’. These are legal in Apple Notes. And were imported to Obsidian with the # character **intact** in the file name. However, # is illegal in Obsidian file/note names. The resulting behavior is that clicking/opening one of these notes actually opens a **new** note with a title/filename of everything up to the #. For example ‘My note’. And the actual note can never be opened. 

I think default Importer behavior might be better to replace or remove the illegal characters. A setting could specify the replacement character, or they could just be taken out entirely.

**Comment by mirnovov** [comment]
Good catch  - it appears this is an issue with other importers as well. Tested this with the Google Keep and the Notion importers, it includes `#`s there as well. Idk about other ones.

@lishid thoughts about adding `[]#|^` to `sanitizeFileName`?

**Comment by lishid** [comment]
Sorry for the late reply, that would definitely be a good idea, thanks!
