### ISSUE TITLE
[OneNote] Nested Section Groups Under Nested Sections Groups Not Discovered

### ISSUE THREAD

**Issue by evans-aiden** [obsidianmd/obsidian-importer#162]
Similar to: #100

When Importing Nested Section Groups, Importer appears to find one layer nested sections under a section group, however when I have a structure like
 _Notebook > Section Group > Section Group > (any extra section groups) > section > page_
Importer can't see those second and third level section groups or sections.
![Screenshot 2023-10-31 at 11 23 00](https://github.com/obsidianmd/obsidian-importer/assets/95153057/5ca8338b-3cf0-461b-a33c-381b29a0cda5)

**Comment by tgrosinger** [comment]
This should be resolved in the latest release - [1.6.1](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.1)
