### ISSUE TITLE
[OneNote] import while maintaining the hierarchy of notes

### ISSUE THREAD

**Issue by vladik-pwnz** [obsidianmd/obsidian-importer#165]
does not save the hierarchy of notes, but simply saves in one row. example from OneNote
![Untitled1](https://github.com/obsidianmd/obsidian-importer/assets/61415206/1a98543c-79ac-4976-899e-f1faa34fe861)

**Comment by legolasdimir** [comment]
This was restated in an issue I created #145 referencing it here for context

**Comment by sol3uk** [comment]
I'm also getting this issue, it's preventing me from making the switch as I used Onedrive quite heavily.
This could be an issue with the fact that Onenote treats these "parent" sections as pages by themselves with actual content and sub pages.
I notice that Obsidian doesn't do this at all and instead opts for treating these as folders. I think the importing needs to be rethought to accommodate this so we get the option to keep our hierarchy whilst also keeping the contents of the parent pages.
Maybe the best way would be to create a folder when a page contains sub pages, then create a markdown file in the root of that folder with the same name (or a name that makes it obvious that it was the parent page's content)
Here's my before and after importing for an example:
OneDrive:
![image](https://github.com/obsidianmd/obsidian-importer/assets/26093813/cbd37d6f-5862-40c8-97b9-32cdea0cd114)
Obsidian Imported:
![image](https://github.com/obsidianmd/obsidian-importer/assets/26093813/327753fa-b4f5-41cd-bdb1-833e54322ee0)
_Lost all structure and hierarchy, still maintained the parent page content, but it's no longer obvious what is related and where pages should be. N.B. The grey box is just redacted content for this post._

**Comment by glinkot** [comment]
Yep, I just found the same.  I thought hierarchy would be preserved (perhaps too optimistically) but I ended up with an alphabetical list of the notes regardless of where they are in the onenote hierarchy.  Would be amazing to preserve it.

**Comment by tgrosinger** [comment]
This should be resolved in the latest release - [1.6.1](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.1)
