### ISSUE TITLE
[OneNote] Import of note will be capped at the point where a YouTube embedding is  

### ISSUE THREAD

**Issue by fatplanediaries** [obsidianmd/obsidian-importer#166]
Tried to import a note from OneNote that contained many YouTube links, as well as embedded players for those links. The importer will only import the note up to the point where the first embedding is, then fail to import the rest of the note. 

Below is an example of one of these OneNote embeddings. 

![image](https://github.com/obsidianmd/obsidian-importer/assets/127848260/d4490b52-e841-453c-9b34-f22677e6f147)

**Comment by tgrosinger** [comment]
This should be resolved in the latest release - [1.6.1](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.1)
