### ISSUE TITLE
Android app crashes on selecting "choose files" for certain data types.

### ISSUE THREAD

**Issue by MrSpeedySmax** [obsidianmd/obsidian-importer#169]
I have recently downloaded Obsidian on my A30s (Android 11).
I have encountered crashing while attempting to import using the official Importer plugin. Clicking "Choose files" crashes the app for certain data types.

Steps to recreate:
1. Open Importer
2. Select [Bear/Evernote/Notion/Roam Research]
3. Click "Choose files"
4. The app crashes

I am attempting in particular to import Notion files.

Any help would be greatly appreciated

**Comment by kepano** [comment]
Can you try on Obsidian for desktop? This is related to #170
