### ISSUE TITLE
[Request] "Processing" message to disappear when import is complete.

### ISSUE THREAD

**Issue by kuredev** [obsidianmd/obsidian-importer#174]
I want "Processing" message to disappear when import is complete.
Because it is difficult to know whether the import is completed or not.

##### html

![image](https://github.com/obsidianmd/obsidian-importer/assets/1259315/a2a6f848-33ef-4831-a211-49d4bd2eac19)

##### Evernote

![image](https://github.com/obsidianmd/obsidian-importer/assets/1259315/ee46aa63-ae4b-4297-b04c-9bb2cd1c5553)

**Comment by kepano** [comment]
Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)
