### ISSUE TITLE
OneNote bug bounty - $300

### ISSUE THREAD

**Issue by ericaxu** [obsidianmd/obsidian-importer#177]
This bug bounty including the following bugs:

- [x] #109
- [x] #120 
- [x] #126 
- [x] #162 
- [x] #165 
- [x] #166 
- [x] #198

**Comment by p3rid0t** [comment]
I'd like to take on this bounty as I am the developer of the OneNote importer. Thanks!

**Comment by adamhill** [comment]
@p3rid0t If you need a tester with large OneNote notebooks from he**. Please reach out, I have plenty with no personal data, just ideas with lots a various kinds of data and embeds.

**Comment by kepano** [comment]
@p3rid0t checking in — do you have an ETA for your PR?

**Comment by p3rid0t** [comment]
Sorry for the long wait time, was quite sick for the previous week, hoping to get it done by the end of this week (hopefully even quicker)

**Comment by ericaxu** [comment]
Update: the bounty has been unassigned due to inactivity. If you're interested in this bounty please comment to let me know!

**Comment by p3rid0t** [comment]
I would like to apply for this bounty again if it is still available. Sorry for the previous inactivity.

**Comment by kepano** [comment]
@p3rid0t Great! Please move forward and submit your PR by February 2. Thank you!

**Comment by kepano** [comment]
@p3rid0t I am adding #198 to this, if that's okay

**Comment by kepano** [comment]
@p3rid0t are you on track to submit your PR today?

**Comment by p3rid0t** [comment]
yes, hoping to do so today! if i'll be unable to submit today, i'll submit it tomorrow ASAP

**Comment by p3rid0t** [comment]
Quick update: bounty tasks are done, just waiting with the PR until I fix issue #164 (too many line breaks), as I found it pretty annoying as well 😅

**Comment by kepano** [comment]
@p3rid0t can you open up a PR for the fixes you have so far? That way we can start reviewing those changes.
