### ISSUE TITLE
unknown attachment: com.apple.drawing.2

### ISSUE THREAD

**Issue by lzilioli** [obsidianmd/obsidian-importer#182]
I just did an import from apple notes, and all of my notes that contained handwritten attachments are (1) missing the attachments and (2) contain `**(unknown attachment: com.apple.drawing.2)**` in their place

**Comment by ahayman** [comment]
Same here.  I have hundreds of hand-written notes that won't import.

**Comment by kepano** [comment]
@lzilioli @ahayman can you try again with Importer 1.5.6?

**Comment by ahayman** [comment]
No, I'm still not getting them.  I no longer see the `unknown attachment` error, but I also don't see any of the drawings.

In addition, the importer is producing a bunch of errors like this:
> Failed: "[Note Title]" because Cannot read properties of undefined (reading 'ZIDENTIFIER')

Also, in quite a few of the files I see this:
> **(error reading attachment)**

The only attachments the importer seems to bring in are scanned documents and older images copied in.  New images I copied in don't show up, and neither do any of my drawings.

I _was_ able to get everything imported by using both the Obsidian Importer and the "Exporter" app downloaded from the App store.  Between the two of them, I could get all my note and their attachments.  However, it took quite a while to copy/move my files between the two export folder structures.

**Comment by evans-aiden** [comment]
I am seeing the same issue as @ahayman  with the ZIDENTIFIER error. using latest version of MacOS and Obsidian Importer.
