### ISSUE TITLE
Evernote: Notes that include $ symbol have broken links

### ISSUE THREAD

**Issue by OM1720** [obsidianmd/obsidian-importer#184]
If evernote-notes title include "$" all images in obsidian-note have broken links to its.

**Comment by akosbalasko** [comment]
Hi @OM1720 ,
unfortunately I cannot reproduce the problem, could you please give us more details about the notes in where the problem occurred? 
If I understand you well, you have a dollar sign in the title of the note in Evernote. This note contains images. And after the conversion the images are not  linked correctly to the converted note, is this the case? 
Do you see some other special characters in the file/folder or even in the name of the image?
Thanks a lot!

**Comment by OM1720** [comment]
HI!

Sorry, I cannot reproduce the problem too. Please, close the ticket.

With best regards, Mike
