### ISSUE TITLE
Import from Notion does not work

### ISSUE THREAD

**Issue by devZu9** [obsidianmd/obsidian-importer#186]
Hello. I am not a native English speaker, I use an online translator, so if there are any mistakes in the text, I apologize immediately.
I tried to do Import several times, at least with the whole database (big file), at least with one partition. I keep getting an error.
I will show clearly, making screenshots, so that it is immediately clear what and how I do.

![image](https://github.com/obsidianmd/obsidian-importer/assets/45079090/a30e5eec-0bd8-4fe4-93dd-a89f1aec91dd)

Getting a zip file from Notion

![image](https://github.com/obsidianmd/obsidian-importer/assets/45079090/08584ee5-9d74-4224-acd6-bb77de453af0)

Running the plug-in

![image](https://github.com/obsidianmd/obsidian-importer/assets/45079090/c9ec60fa-4ca9-4d68-979c-e47253d0fbd4)

![image](https://github.com/obsidianmd/obsidian-importer/assets/45079090/698d50a3-bd51-47b6-a3b7-83dbe1b98b94)

![image](https://github.com/obsidianmd/obsidian-importer/assets/45079090/07712a0a-099d-4c4c-9c0d-e701fea666e3)

I get an error and it is unclear what to do next.

I attach a file taken from Notion
[1229348f-261c-4594-88a7-a214be30f4eb_Export-9eeedcbe-de31-4459-88f1-e9a7212e1a43.zip](https://github.com/obsidianmd/obsidian-importer/files/13573485/1229348f-261c-4594-88a7-a214be30f4eb_Export-9eeedcbe-de31-4459-88f1-e9a7212e1a43.zip)

p.s. 
- Obsidian v.1.4.16
- windows 10 x64 Pro 22H2
- Core i5-4670
- 32GB RAM

**Comment by kepano** [comment]
You have selected the wrong export format in Notion. Please follow the instructions here:
https://help.obsidian.md/import/notion

The export format should be HTML
