### ISSUE TITLE
[Evernote] Tag hierarchy/structure is not imported

### ISSUE THREAD

**Issue by grm9762** [obsidianmd/obsidian-importer#187]
Hey there! 

I have created an .enex file with Evernote Legacy v. 7.14.1 on my Mac.

I work exclusively with tags in Evernote and have built up a very extensive tag structure.

Unfortunately, this structure (nested tags) is lost when importing. Only the tags that are actually assigned to notes appear in Obsidian. This means that the tag headings, which are only for the overview and are not assigned to any notes, are not present in Obsidian. 
 
Is there a workaround for this?

Thanks for your support!

**Comment by kepano** [comment]
Supported in Importer 1.6.0 but requires some work in Evernote to prepare for import, see documentation
https://help.obsidian.md/import/evernote
