### ISSUE TITLE
Ability to import from clipboard [spec for mobile]

### ISSUE THREAD

**Issue by tayoufabrice** [obsidianmd/obsidian-importer#191]
## Description
I enabled the "auto convert into MD" option from setting but the HTML I paste is never converted. I assume it may be an assue about the data type in the clipboard. Also I suspect the content of my HTML which is only a fragments (starting at a div)

## Reproduce

- Set Obsidian in editor "Auto Convert to markdown= on"
- Copy HTML code to clipboard 
- Create an empty note and paste (I also tried to paste in source code view)

## Context 

The platform : mobile
Issue: Feature request
Obsidian version: 1.4.16 (114)

**Comment by tayoufabrice** [comment]
I'm following my request by an idea:

- A drop-down to pick the format in the clipboard
- A text box to paste in

OR simply another option in the list of current ones (Notion, Apple Note, HTML files ...)

**Comment by kepano** [comment]
This is out of scope for the Importer plugin. I would recommend opening a feature request on the Obsidian forum.
