### ISSUE TITLE
[Apple Notes] Image file name conflict results in "(error reading attachment)"

### ISSUE THREAD

**Issue by solidgonk** [obsidianmd/obsidian-importer#192]
When importing from Apple Notes, "(error reading attachment)" may occur.

I suspect that this is related to a naming conflict of images when they're placed in the same attachments folder. I have a dozen or so images named "pasted graphic.png" (you can search this in the Apple Notes search field), and they are all coming up with that error.

I'm not sure if the solution here is to rename the filename (i.e. "pasted graphic-01.png") during import?

**Comment by solidgonk** [comment]
This also appears to affect other attachments with duplicate names, such as html.

**Comment by Johannnnes** [comment]
Same here, with .TIFF, amongst others

**Comment by alexrecuenco** [comment]
Same here, 

I have a myriad of PDF documents that I just scanned, so they are called "Scanned documents" and it failed to import many of them correctly when they are on the same note.

Also, when fixing this, keep in mind that "filenames" in notes can have characters that are not valid filenames (like `/` or `\n`), and those notes work on iOS and, they don't work on macOS "sometimes"  (at least last time I tried, they might've fixed it in the last months, it was still broken around November 2023)

**Comment by solidgonk** [comment]
Appears to be fixed in #310

**Comment by tgrosinger** [comment]
Great, thank you for the update!
