### ISSUE TITLE
[Evernote] Fails to set some notes' dates

### ISSUE THREAD

**Issue by przemhb** [obsidianmd/obsidian-importer#194]
I have just used 1.5.6 to import ENEX notes. Some of the 394 notes were not set dates according to the ones stored in the ENEX file. I end up with writing Python code to fix this. Interestingly os.utime() failed to set those dates also and I was forced to use win32file.SetFileTime().

**Comment by akosbalasko** [comment]
Hi @przemhb ,
Could you please give us a bit more details about the problematic notes? Do you see any aspect that distinguishes the failed ones from the notes converted correctly? The key point would be that what you recognized, the failure of os.utime().
Thanks a lot!

**Comment by akosbalasko** [comment]
@przemhb , it's strange definitely. 
But what you mentioned in your first comment made me think: "Interestingly os.utime() failed too". It would mean that something has failed on a deeper level.
I checked the code and fs.utimesSync (os.utime equivalent in NodeJS) is not covered by try-catch, so if it fails, it will make the whole note-conversion fail, even if everything goes well until that point. I think handling possible exceptions in this function would be a good patch. 
May I ask what you saw as a failure?

**Comment by przemhb** [comment]
@akosbalasko In the case of failed import a note's modification date and time was not set as in the ENEX file, but to current time (or creation time - not 100% sure after those few weeks). As an effect sorting by modification date was flawed with some old notes appearing on the top of the list.

**Comment by akosbalasko** [comment]
@przemhb , okok thanks! And when you run the import last time, you mentioned that it went well flawlessly. Do you mean that the import itself worked well and set the correct creation dates without the python script?

**Comment by przemhb** [comment]
@akosbalasko yes, import alone went just fine, so I wasn't forced to use my python script. Modification dates were as in source ENEX.
