### ISSUE TITLE
[OneNote] Sign in often not possible

### ISSUE THREAD

**Issue by kabokabeso** [obsidianmd/obsidian-importer#196]
Unfortunately, the sign in often does not work. Either the redirection even does not work or no Sections are shown. Also I have the new problem, that I am redirected to my work outlook account I do not want to import.

**Comment by Iamanshuaditya** [comment]
hey @kabokabeso how to reporduce this . i am able to sign in perfectly

**Comment by agowa** [comment]
@Iamanshuaditya typical MS problem... Sign in with a corporate account and then you've sometimes to clear cookies before you can log in with another one as trying to log out fails...

**Comment by kepano** [comment]
This needs more detail or should be added to another issue such as #233 or #228
