### ISSUE TITLE
[OneNote] Attachment imports fail for duplicate file names

### ISSUE THREAD

**Issue by SSzretter** [obsidianmd/obsidian-importer#198]
If the same filename exists with note(s) the attachments are failing 'because Error: File already exists'.  
It should probably rename the attachment (1, 2, 3, etc.) in a loop so those attachments are not lost during import.

**Comment by krizman** [comment]
Probably a duplicate of #126. I also have the same issue where I can't import a single notebook from OneNote. Copy-pasting content is also a futile task since for example the checkboxes get copied over as inline base64 encoded images ☑️ 😅

**Comment by lniass** [comment]
I stopped migrating to Obsidian because I had too many files considered as "existing" that I did not want to lose.

Hoping there is soon a solution.

**Comment by tgrosinger** [comment]
This should be resolved in the latest release - [1.6.1](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.1)
