### ISSUE TITLE
Evernote: imported notes do not include source links embedded in Evernote original

### ISSUE THREAD

**Issue by toddz262** [obsidianmd/obsidian-importer#200]
When material is pasted into Evernote from the web, a URL for the source page is also saved. This URL doesn't appear as a tag or within body copy, but as a separate field in the Evernote interface.

This URL isn't preserved in Obsidian pages produced by the importer.

When the same ENEX file is imported to Joplin, these URLs do appear in Note Properties.

Could the Obsidian importer be modified to include the source URL, perhaps as the first line of body copy? It's a rather important piece of data.

**Comment by kepano** [comment]
This should be saved as a property, called `url` or `source`
