### ISSUE TITLE
[Evernote] Import loses files with the .dxf extension

### ISSUE THREAD

**Issue by timurtimurtimurtimur** [obsidianmd/obsidian-importer#201]
Importing files from Evernote, for example with the .dxf extension, 
export works fine if the exported note is imported back into Evernote with all files in place.

**Comment by timurtimurtimurtimur** [comment]
Hi. I attached the file to the letter.

Тимур Рубан,
Звоните, WhatsApp, Telegram  +7 911 991 91 71
MagentaCo.Ru <http://www.magentaco.ru/>   +7 812 970-90-77
197198 Санкт-Петербург, ул. Большая Пушкарская д.10


пн, 29 янв. 2024 г. в 21:57, Akos Balasko ***@***.***>:

**Comment by akosbalasko** [comment]
hi @timurtimurtimurtimur ,
Unfortunately github banned the attachment, pls send me directly, here is my email address:
akos0215@gmail.com

Thanks a lot!
