### ISSUE TITLE
Evernote bug bounty - $300

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#204]
## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $300 USD
**Timeframe:** 10 days

## Requirements

Bug bounty including the following Evernote bugs. Most of them are related to improper formatting, or missing conditions in file names.

- [ ] #24
- [ ] #187
- [ ] #26
- [x] #184
- [ ] #185
- [ ] #190
- [ ] #194
- [ ] #200
- [ ] #201

**Comment by kepano** [comment]
@akosbalasko let us know if you're interested in picking this up!

**Comment by akosbalasko** [comment]
Hi @kepano ,
Thanks for tagging me!
Sure, I'm definitely interested, let me check the issues and get back to you tomorrow! (It's almost midnight here)

**Comment by akosbalasko** [comment]
Hi @kepano ,

According to the contribution description, here is my _formal_ application to the bounty: 
**Why would I be the best fit to the job:** 
Because I developed and actively maintain Yarle, I know what is where and how it is structured logically.
**How I would approach the requirements:**
This batch contains different type of issues: features(#200, #26) or bugs( #184, #185, #190), and  detailed in various level. 
- Some of them can be achieved as they are. 
- Some others (like #24  or #187 ) phisically cannot (Evernote does not export the required information into the enex). Therefore these latter issues would require workarounds involving manual pre-steps from the users at Evernote-side.
- Some others are more general (#194 #201), I'd need more info about the problem. For instance I tested #201 , but it importing DFX works for me totally, so I think the problem is not related to the extension of the attachment. 

Thanks again!

**Comment by kepano** [comment]
I have assigned the bounty to you. Please submit your initial PR by end of day February 6th.

Let's start with the easiest and most obvious ones first. If you have any questions about requirements on specific issues please post them here.

It sounds like we should consider ignoring #24 and #187, unless you can think of a way to support those?

**Comment by akosbalasko** [comment]
Hi @kepano ,
I have some questions about some of the issues: 
#184 : I cannot reproduce the problem, $ sign within note title works (it contain an image as well), linked. 
#201 : same, it looks like that the issue description (e.g. the DFX extention causes problems) doesn't point the real problem. 

What is your expectation, may I contact with the reporters and ask for more details? 

Regarding #24 and #187, I think there is a workaround to achieve the expected result, but it requires manual modification within Evernote: as enex doesn't contain neither the hierarchy of tags nor the notebook stacks, tags and notebook names could be "flat" out with some predefined delimiter, and we could use that property to store the full-path of the notebooks and tags respectively. But this must be done by the import within Evernote. The preferred delimiter could be highlighter in the documentation of the Importer.
So assuming that the delimiter would be "<YARLE_DELIMITER>" and we have tag1 -> tag2 in notebookStack -> notebookA , the notebook should be renamed to notebookStack<YARLE_DELIMITER>notebookA and the tags to tag1<YARLE_DELIMITER>tag2.
I'm afraid this is the best what we can do with this badly designed enex export of Evernote. 
What do you think, is it acceptable for Obsidian users to do?

**Comment by kepano** [comment]
@akosbalasko please go ahead and get additional detail from the users on issues #184, #194, #201

For #24 and #187 it sounds acceptable, but can you start by writing a bullet point version of the documentation first? I don't use Evernote myself so I am not clear how the user would go about doing this. What would the steps be for the user to add the delimiter?

**Comment by akosbalasko** [comment]
@kepano , sure sure I'll start with the bullet points then.

One other thing: during the implementations I realized that generating the title "inside" the note with header1 doesn't look good as the filename itself appears at the top. May/Should I remove it? 

<img width="676" alt="removing-titles" src="https://github.com/obsidianmd/obsidian-importer/assets/11886731/394c01d1-8881-4b97-a6e0-fa1affe7b83b">

**Comment by kepano** [comment]
Yes, we should remove the H1 title. It's not necessary and it's also different from how all other Importer formats work. Later we can add a generic option for all import types to add an H1, since this isn't Evernote-specific.

Regarding unit tests, I will leave this up to @lishid. I don't think it's necessary but he may disagree. In general we prefer to avoid external dependencies.

**Comment by lishid** [comment]
I think we are ok to not have tests for now. Importer isn't really a moving target unlike a living and frequently updated app so I think it would be ok for now to keep it simple. We could include some test cases in the `/tests` folder though.

**Comment by kepano** [comment]
@akosbalasko Yes, that makes sense to me. Go ahead. The tag notation seems intuitive enough. I don't have a strong opinion about the right delimiter for notebook stacks, what you have proposed sounds okay to me.
