### ISSUE TITLE
[OneNote] Fill `File Properties` during import

### ISSUE THREAD

**Issue by Korayem** [obsidianmd/obsidian-importer#212]
I've been using OneNote since 2004, I want to migrate it into Obsidian but `Created At` and `Last Updated At` aren't imported though they're supported by Obsidian
![image](https://github.com/obsidianmd/obsidian-importer/assets/198332/d258a3db-cb39-4183-9ebf-61ae756b9f5d)

**Comment by kepano** [comment]
The creation date and modified date should be applied to the file itself at the file system level.

When you look at the file in File Explorer you should see those dates. Can you confirm?

Importing those dates as properties is not currently supported but you could populate those using a separate script or plugin.

**Comment by Korayem** [comment]
@kepano thanks for your answer. Indeed you're right.

I looked up how I can script this and this is my solution. However, when I do OneNote import, Templater doesn't trigger on created notes. Any ideas?

Here are the steps I took:
1. Install [Templater](https://github.com/SilentVoid13/Templater) plugin
2. Create the `/templater/insert file property.md` and add the following script
```
---
Created at: <% tp.file.creation_date() %> 
Last updated at: <% tp.file.last_modified_date() %>
---
```
3. Go to `Templater` Settings and enable `Folder Templates`, which basically tells Templater to run a specific template whenever a new Note is created inside that folder. Mine is `OneNote` which I use to import notes into.
![image](https://github.com/obsidianmd/obsidian-importer/assets/198332/cb0c726e-7029-49a8-9187-edec84997d99)

**Comment by kepano** [comment]
I would recommend asking on the forum or Discord as this out of the scope of Importer.

**Comment by Korayem** [comment]
@kepano To debug the root cause, I created a New note manually inside `OneNote` and the above solution indeed worked. Templater inserted the `File Property` block.

The issue is with Obsidian Importer. For some reason, when it's importing files from OneNote and creating notes, it's not firing `file created` hence Templater isn't detecting any new files.

So I plz re-open this

**Comment by Korayem** [comment]
Cross-linking a similar discussion [on Obsidian forums for reference](https://forum.obsidian.md/t/make-file-metadata-and-properties-separate-concepts/75664). I posted there also about this ticket to garner more people into the discussion.
