### ISSUE TITLE
Import from Notion doesn't work, despite HTML format selected in Importer

### ISSUE THREAD

**Issue by vincenttttt** [obsidianmd/obsidian-importer#219]
Hello! I am finally switching over to Obsidian and quite excited about it. 

I have a small hiccup when using the Importer with my .zip from Notion workspace. 

Despite being exported in HTML, I see this error:
<img width="334" alt="Screenshot 2024-03-09 at 15 52 47" src="https://github.com/obsidianmd/obsidian-importer/assets/19893494/8c1c89f8-cda4-4f28-b732-faae342bbdcd">

<img width="551" alt="Screenshot 2024-03-09 at 15 53 43" src="https://github.com/obsidianmd/obsidian-importer/assets/19893494/d606d587-a419-4140-9d97-9aa3108b17c5">

I've followed all the steps of [this page](https://help.obsidian.md/import/notion) with no luck. Does anyone know where this is coming from? I have quite a large number of pages and files (2k+), so it's critical I use the importer to start using Obsidian. 

Many thanks for your help!

**Comment by kepano** [comment]
Can you please copy/paste the error?

**Comment by vincenttttt** [comment]
Sure thing! 

The full error is `Failed: "809bf26a-d15a-40a1-aa58-4e81e44f334c_Export-acf3593e-75cc-4a6e-bfc2-2eca1fad00ab.zip/Export-acf3593e..."`

I also see that error on a window at the top right: `Notion Markdown export detected. Please export Notion data to HTML instead.`

**Comment by vincenttttt** [comment]
I've finally found where this came from. Notion doesn't automatically remove pages/content one doesn't have access to (as owner/creator) from the export, so it creates a glitch in the import. I removed some pages that were of concern within Notion, and this was fixed. Maybe it would be worth adding to troubleshooting. Thanks!

**Comment by oscartorres-10** [comment]
> I've finally found where this came from. Notion doesn't automatically remove pages/content one doesn't have access to (as owner/creator) from the export, so it creates a glitch in the import. I removed some pages that were of concern within Notion, and this was fixed. Maybe it would be worth adding to troubleshooting. Thanks! 

@vincenttttt what are "pages that were of concern within Notion"? 

can you explain more in detail and give some examples?

i'm experiencing a similar issue and looking for a workaround

**Comment by vincenttttt** [comment]
There were sub-pages in another workspace in Notion, I was switching from an account to the other within Notion but obviously this didn't work out in the export. Hope that makes sense?

**Comment by oscartorres-10** [comment]
that makes sense, yes! thanks for mentioning it

**Comment by zhishusang** [comment]
Export-3869339c-a8b8-4769-8cc8-485a8064f947-Part-1.zip"  how to deal with it？
