### ISSUE TITLE
OneNote importer does not work

### ISSUE THREAD

**Issue by Qvinto1** [obsidianmd/obsidian-importer#220]
I just paid for a subscription to Obsidian and started importing my notes from OneNote. 

The importer just does not work and there are many issues:
- it stalls after a few seconds
- folder hierarchy is not preserved
- it copies the same image files into multiple pages where the image file was not originally present in the one note library

There are many serious issues. It would be great if this could be addressed. Thank you!

**Comment by kepano** [comment]
There is a project to address bug fixes for OneNote that is in progress, see #177. If you don't see your issues listed please open separate bug reports with steps to reproduce.

Also, be aware that Importer is a community project. It's independent from your subscription to Obsidian Sync.
