### ISSUE TITLE
[Roam] import settings/feature requests

### ISSUE THREAD

**Issue by dropcase** [obsidianmd/obsidian-importer#236]
Hi, I'm working on importing my Roam graph (~7200 notes) and looking for a few updates to help with the migration.

- Option to replace "invalid" characters in file names with a default (or user-choice option), possibly with adding the original naming as the `title` value in YAML frontmatter
- Option for removing one level of indented bullets, tested as working with this sed string: `s/  \* /* /g`
- Option for removing bullets from headers, using these for H3 and H2 as an example: `s/\* ###/###/g` and `s/\* ##/##/g`
- Option to use the `create-time` and `edit-time` from the [Roam JSON Schema](https://roamresearch.com/#/app/help/page/Nxz8u0vXU) in YAML frontmatter as `created` and `updated` dates

I'll share updates if I'm able to test anything on my local system. Thanks!

**Comment by dropcase** [comment]
Updated the PR with a new commit, added TZ and corrected title YAML setup

**Comment by tgrosinger** [comment]
PR merged!
