### ISSUE TITLE
Importing .enex do not save folders

### ISSUE THREAD

**Issue by Josema** [obsidianmd/obsidian-importer#24]
Is there a way to respect my evernote folder structure when importing the .enex file?

**Comment by ericaxu** [comment]
Do you mind sending me a sample .enex file that contains the said folder structure for testing purposes? Please make sure there's nothing confidential in it. Or you can DM me on Discord and send it that way if you prefer.

There's a chance that the folder structure doesn't get exported in the .enex file though. See https://discussion.evernote.com/forums/topic/144090-how-to-backup-in-enex-including-folder-structure/

**Comment by Josema** [comment]
I'm afraid I would have to remove all my notes in order to do that. This is what I do basically 
![image](https://github.com/obsidianmd/obsidian-importer/assets/1819888/14e5ebe5-359b-476f-9e4f-b6a4da9e6881)
 
But, yeah probably the reason is that evernote is not exporting the folder structure. If you want I can generate a fake folder structure, export it as .enex and you cant test it.

**Comment by Josema** [comment]
There is another problem. When I import folders individually, It says that is importing 73 notes. But then I count and there is only 41.

**Comment by ericaxu** [comment]
> There is another problem. When I import folders individually, It says that is importing 73 notes. But then I count and there is only 41.

You should open a separate issue for a separate problem.

**Comment by ericaxu** [comment]
@Josema From your screenshot, is "dev" a notebook stack? Evernote doesn't seem to have folders, so I want to make sure we're on the same page.

https://discussion.evernote.com/forums/topic/40701-evernote-sub-folders/

**Comment by Josema** [comment]
> @Josema From your screenshot, is "dev" a notebook stack? Evernote doesn't seem to have folders, so I want to make sure we're on the same page.
> 
> https://discussion.evernote.com/forums/topic/40701-evernote-sub-folders/

Yes it is. That post is from 2013, probably they implemented lately.
![image](https://github.com/obsidianmd/obsidian-importer/assets/1819888/62fe6a36-0d51-4d60-9c28-e01aa542762e)

**Comment by ericaxu** [comment]
@Josema There has been lots of updates to Importer. Just to confirm is this still happening? Thank you!

**Comment by Josema** [comment]
Still having the same problem, it does not respect the folder structure. Not sure if I'm doing something wrong. Using Importer `1.4.0`.

This is my `dev` structure in evernote:
![image](https://github.com/obsidianmd/obsidian-importer/assets/1819888/08de7638-383e-4c22-91f7-f8544a7c09b5)

And this is what I get after importing:
![image](https://github.com/obsidianmd/obsidian-importer/assets/1819888/63ec2cd1-f6f5-4302-82b0-ed01b5d4f8af)

**Comment by ericaxu** [comment]
Got it, thank you for the update!

**Comment by kepano** [comment]
Supported in Importer 1.6.0 but requires some work in Evernote to prepare for import, see documentation
https://help.obsidian.md/import/evernote
