### ISSUE TITLE
[Notion] Math blocks inside Callouts don't render correctly

### ISSUE THREAD

**Issue by enricobolzonello** [obsidianmd/obsidian-importer#259]
As an example, this is a callout in Notion:

<img width="700" alt="Screenshot 2024-06-04 alle 23 20 41" src="https://github.com/obsidianmd/obsidian-importer/assets/73855124/5983e5bf-da6f-4d3d-9cf8-32baddca9965">

and after import in Obsidian:

<img width="600" alt="Screenshot 2024-06-04 alle 23 22 43" src="https://github.com/obsidianmd/obsidian-importer/assets/73855124/b43af670-d8eb-40e1-be9b-3c0e71f10cb2">

This issue repeats on all files, but only on callouts. Math blocks outside callouts render correctly

**Comment by felciabatta** [comment]
I get the same thing. Having a quick look, I think the issue is with line 58 & 62 of [notion/convert-to-md.ts](https://github.com/obsidianmd/obsidian-importer/blob/83a6d6c474a94f4fcc30f09acb9566b2de0c1fd9/src/formats/notion/convert-to-md.ts)?

```
58  fixNotionCallouts(body);
62  fixEquations(body);
```

I don't know much about typescript but I suspect that the following line isn't working properly for equations nested in callouts:

```
230  const katexEls = body.findAll('.katex');
```

@lishid @j-palindrome is it because `fixNotionCallouts()` is called **before** `fixEquations()`?

**Comment by felciabatta** [comment]
I have tested this with a local copy of the repo; moving the `fixEquations(body);` line before the `fixNotionCallouts(body);`, has _half_-fixed the problem for me.

The `$$` signs appear to be inserted correctly. As a minimal example:

In Notion:
<img width="725" alt="Notion callout with LaTeX" src="https://github.com/user-attachments/assets/e112f092-9702-4ab5-918b-b453c35d49c9">

Imported MD Source (Original):
```markdown
> [!important]  
> My CalloutGiven some function @import url('https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css')f(t)\small f(t)f(t)
```

Imported MD Source (With Line 58–62 Amended):
```markdown
> [!important]  
> My CalloutGiven some function @import url('https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css')$\small f(t)$
```

It might still look bad, but it's half the issue resolved — the two duplicate `f(t)` math expressions are gone, and the `$$` signs have reappeared.

The only remaining issue is that the `@import url()` statement is still there, and the first `$` needs to be preceded by a space to ensure that the LaTeX renders.

Also, as a second bug, the callout title should appear after the `[!important]`, as it is currently concatenated with the first line of the callout body.

So, if both issues are fixed, I believe the MD source should look like this:
```markdown
> [!important] My Callout
> Given some function $\small f(t)$
```
