### ISSUE TITLE
[Apple Notes] issue with .jpg files

### ISSUE THREAD

**Issue by FilipLaz** [obsidianmd/obsidian-importer#272]
I have a problem with importer that didn't exist before.
I imported apple notes on 16th of November of 2023(I named the folder based on the date I tried to import). 

I am retrying it today again and import if failing for attachments(it appears mostly for .jpg files)

This is how note that had .jpg file looked before:
![image](https://github.com/obsidianmd/obsidian-importer/assets/4378518/5e00a218-b1bc-415f-8c4d-6d219d1fe5af)

This is how it looks today on 24th of June 2024, there are many errors like this ( **(error reading attachment)**) 
![image](https://github.com/obsidianmd/obsidian-importer/assets/4378518/ed469ef2-308d-406a-b660-113848fc836a)

I am using Sonoma 14.5, fresh install of Obsidian - I tried several times always the same errors for .jpg files.

**Comment by kemelinux** [comment]
I have the same error in about 90% of the imported Apple Notes. Only a few show an embedded image, the others show the "error reading attachment" message. MacOS Sanoma 14.6.1 with Obsidian Version 1.6.7 (Installer 1.5.3) and Apple Notes Version 4.11 (2817).  Most of my Notes were created in previous versions of Apple Notes BUT I am also experiencing it with Notes created in the current version of Apple Notes.

**Comment by FilipLaz** [comment]
This is not the issue for me after latest updates to mac and obsidian importer.
