### ISSUE TITLE
Import from Mozilla Firefox Extension

### ISSUE THREAD

**Issue by irwanwr** [obsidianmd/obsidian-importer#275]
Wishing to have a feature for ability to import files from Mozilla Firefox extension(s). 

I am currently using [OurStickys - Sticky Notes on every page](https://addons.mozilla.org/en-GB/firefox/addon/ourstickys/) and [Textmarker ](https://addons.mozilla.org/en-GB/firefox/addon/textmarkerpro/)of Firefox extensions. There are many other similar extensions available, but I only use these two actively for now. 

The problem is that both has become limited in their functions. So, I thought it would be better to be able to download/import their files and store them locally and even put them into Obsidian notes (got this idea after I've learnt that there's an app called Obsidian as alternative for other "note-things-apps" that I've used).

- OurStickys's original author passed away few years ago. It's just "revived" by unknown people on Mozilla this month. It lost its ability to synch/share notes over the web. It was also designed to share notes among teachers/lectures and students. There's an option to export/import notes from the extension though. 
- Textmarker is no longer developed, only maintained. As the author has been taken away by RL things. There's an option to download the history and make backup of the highlights. 

These probably are still the best extension in my opinion based on how they work. Both make "anchored" or "pinned" highlights/notes on specific part of a web page. Textmarker highlights right on text on a webpage. OurSticky's notes stays on a line where they are made, even the page can be scrolled long way down. 
These two extensions make their notes/highlights in .json files. 

I wonder if it's possible to retrieve/import their notes/highlights files into notes in Obsidian. 

Pardon my English. Thanks.

**Comment by kepano** [comment]
This is out of scope for this plugin. I would recommend using another tool to export and convert these files to Markdown.
