### ISSUE TITLE
HTML attachments - $300

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#28]
## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $300 USD
**Timeframe:** 7 days

## Requirements

Improve the HTML importer by adding support for attachments

- [ ] Add support for attachments (images, video, audio)
- [ ] Follow the user's setting for `Default location for new attachments`
- [ ] Use Obsidian-style embed links `![[image.png]]`
- [ ] Avoid importing icons/logos that are not part of the content of the page

**Comment by polyipseity** [comment]
I might be interested. I have plugins in the community plugins and the requirements are simple enough, so I believe I could do this one.

But where would one ask for clarification of requirements though? Like I am wonderimg whether "maintain folder structure" means I need to create subfolders under the attachment folder or a flat structure would do. Also, should we work from the `master` branch or some other branch like `html-import`?

**Comment by polyipseity** [comment]
Right, I think I understand now. Thank you.

**Comment by kepano** [comment]
Yes, you can apply. [See contribution guidelines.](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md)

**Comment by polyipseity** [comment]
Yea, I confirm that I am applying.

(I must be bad at language or something, I thought my intention to apply is
already clear. 😅)

**Comment by kepano** [comment]
To apply please provide the following. We will wait a few days to see if other developers are interested.

- 1-2 sentences about why you would be a good fit
- 1-2 sentences about how you would approach the requirements
- Links to code samples, e.g. Obsidian community contributions

**Comment by polyipseity** [comment]
1. I think that I have probably spent enough time with the Obsidian API to know what and how API methods and classes should be used.
2. (Two sentences is a bit short, but I will try to shorten the sentences.)
    1. Load files and call `htmlToMarkdown`. (currently implemented)
    2. Identify external embeds `![alt](link)`.
    3. Filter links either by extension in the URL (no request needed, but could be inaccurate or unavailable) or returned content type (requires a request; filter by checking whether the type starts with `image/`, `audio/`, or `video/`). This filter could be user-configurable in the import dialog. If configurable, filtering by file extension is more understandable to end users than content type.
    4. Collect all the links and deduplicate them (embeds pointing to the same URL).
    5. Download them using `requestUrl` and put them into the user-configured (`Default location for new attachments`) attachment folder. If filenames collide, add an increasing number to distinguish them (`File 1.png`, `File 2.png`, `File 3.png`...). Ideally, there should be a separate count for successful, failed, and skipped (filtered) attachment downloads in the results.
    6. Replace external embed links with either wikilinks or Markdown links according to the setting `Files & Links > Use [[Wikilinks]]`. Embeds with failed downloads are unchanged.
    7. The steps from ii to v should run concurrently (async) with i and vi so that the downloads start when the first link in the first file is identified instead of waiting for all the links in all files to be identified.
    8. The current implementation reads, processes, and saves each HTML file one by one in  a `for` loop (file reads and writes are comparatively slow compared to code execution), which can be improved by using `Promise.allSettled` instead: https://github.com/obsidianmd/obsidian-importer/blob/77155aef1576bd5c5b9b8b460d8e7e8be14ae0cf/formats/html.ts#L31-L42
3. A plugin is a lot of code sample to go through, so I will link the PR instead: https://github.com/obsidianmd/obsidian-releases/pull/1472. There are also 2 ongoing PRs: https://github.com/obsidianmd/obsidian-releases/pull/2189, https://github.com/obsidianmd/obsidian-releases/pull/2197

**Comment by polyipseity** [comment]
Since Node APIs are used anyway, we can convert local file paths to and from file URLs using `pathToFileURL` and `fileURLToPath`. Then if the protocol of the URL is `file:`, read the file directly instead of going through `requestUrl` and copy the file to the vault.

For resolving local relative paths URLs, the `URL` constructor has a `base` second argument, so doing `new URL(linkPath, pathToFileURL(htmlPath))` will correctly resolve them.

**Comment by kepano** [comment]
Something I have been wondering about is how to make sure we only import the attachments that are related to the content of the article. Many web pages have logos/icons embedded in the HTML but we probably should only import the images/etc that are in the content of the page.

**Comment by polyipseity** [comment]
Perhaps image size could be used. If the image is within 64 px x 64 px (or user configured size), then it is considered an icon or logo. The external embed link could be removed if it is an icon or logo.

**Comment by kepano** [comment]
@polyipseity You are assigned! Please make sure to submit your PR by end of day (GMT) on August 4th, 2023. Thanks! 

Join the #plugin-dev/importer channel if you have any questions: https://discord.gg/obsidianmd

**Comment by kepano** [comment]
We are increasing the bounty reward to $300 since this was a bigger project than anticipated.
