### ISSUE TITLE
GoodNotes import request

### ISSUE THREAD

**Issue by kshakib22** [obsidianmd/obsidian-importer#280]
GoodNotes is a very popular app for the ipad and importing notes/diagrams from there would be a life saver! Plus goodnotes diagrams are vector images which I prefer to be transferred

**Comment by kepano** [comment]
It seems like Goodnotes has very limited export options. [According to this support page](https://support.goodnotes.com/hc/en-us/articles/7353742824975-Export-documents-or-pages) the available export formats are:

> - Goodnotes document - can only be opened in Goodnotes
> - PDF (editable/flattened)
> - Image

Do you have an example of a "Goodnotes document"? None of these formats are particularly well suited to a clean conversion to Markdown.

**Comment by kshakib22** [comment]
I just realized between iPad & Mac Goodnotes you can just cross copy-paste into obsidian and it pastes automatically as a png. Thanks!
