### ISSUE TITLE
登入onenote 点击sign in无反应

### ISSUE THREAD

**Issue by JUELULU** [obsidianmd/obsidian-importer#283]
登入时点击sign in没有跳转链接
![屏幕截图 2024-07-26 202744](https://github.com/user-attachments/assets/056ecc7d-c182-4261-9b51-477f40c546d6)

**Comment by kepano** [comment]
Do you see any errors in the console?

**Comment by winds-D** [comment]
<img width="208" alt="1" src="https://github.com/user-attachments/assets/8a69a9a9-9682-4d7f-9ebb-9c26b27fdad8">

**Comment by kepano** [comment]
Closing in favor of #233 and #228
