### ISSUE TITLE
Importing from OneNote completely broken

### ISSUE THREAD

**Issue by SeverinAequus** [obsidianmd/obsidian-importer#285]
Scope: Aside from the bonus bug, this report is regarding the importation of data from Microsoft OneNote. I did not try any other import modes and will assume that they all work flawlessly.  

[ Warning: This bug report is long, cites numerous bugs all together because, frankly, the thing is so broken that the specific details of the bugs really don't matter. The whole thing needs to be rewritten from scratch. I'm serious. I've been a software architect responsible for major commercial software products for more than two decades and I would never dare to release a product in the condition this is in. I'm beyond disappointed in the quality of this component. So as you read this report, expect to be talked down to. Frankly, you deserve it. This product should never have been released in such atrotious condition. ]

Where to begin? Did you even try this functionality even once? It's completely broken. There's no way I can use Obsidian if I can't import the tens of thousands of notes I have in OneNote. Here are the main issues I encounterted, but I have no doubt there are many more:

BONUS BUG: I originally put this at the end, but since we both know you won't make it that far, I'm putting it up here because it's a rather huge bug in Obsidian (not in your plugin). You know how there's an option in the main settings dialog to change the behavior of the scroll wheel to zoom instead of panning the content? Yes, it's there. I'm not going to find it for you, but it's in there. Now.... try setting that bad boy to "zoom". Now close the settings dialog and minimize Obsidian. Mouse over to your Chrome window and try using the scroll wheel... Doh! I don't know how you managed that, but someone got a tad over-zealous in their implementation! The only way I know of to accompluish something like that would be to hook the mouse interrupt, but I didn't think you could do that from user space. Nonetheless, whatever they did, it needs to be changed to listening for mouse events from the Win32 API in just your window! Fortunately, when you close Obsidian, the scroll wheel behavior returns to normal without any need to restart Chrome.

The fact that the behavior described in the previous paragraph is even possible worries me. This issue may even need to be escalated to Microsoft as a breach in their security measures to isolate applications. Don't think that they won't listen to you. They will. I've logged bugs against the .NET Framework and had them fixed promptly and even released as public hotfixes. Especially if you include code that demonstrates the issue, you'll most certainly get their attention.

But now lets turn our attention to your very specific part in this horrific mosh pit you call software:

1. It only got into the second notebook before simply giving up. The first notebook only had 2 notes in it. The second was pretty typical with about 1,000 notes in it. The importer just quit randomly around 300 or so notes in. The other 20 or so notebooks were simply ignored despite being checked in the very poorly-designed dialog that requires the user to scroll where it isn't obvious to do that and "Select All" on every workbook individually with no real "Select All" button available. Very tricky, but I'm catching on to your bullshit.

2. Error log:
Failed: "Bitcoin Splits : Gold and 2x" because Error: File name cannot contain any of the following characters: * " \ / < > : | ?
Failed: "Statement of Facts for Eviction Trial " because Error: File names cannot end with a dot or a space.
Failed: "Notes" because Error: File names cannot end with a dot or a space.
Failed: "Retaliation: Internet" because Error: File names cannot end with a dot or a space.
Failed: "Retaliation: Raising Rent from $0 to $600" because Error: File names cannot end with a dot or a space.
Failed: "Improper Notice" because Error: File names cannot end with a dot or a space.
Failed: "Storage Inventory (before/after) " because Error: File names cannot end with a dot or a space.
Failed: "Storage Inventory (raw)" because Error: File names cannot end with a dot or a space.
Failed: "08-5-2022" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "SII Status (formal/public version)" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "FB Post: You're all Assholes" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "FB Post: Sybil" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "FB Post: Plea for Help (long version)" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "FB Post: Status of Move-Out" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "Message: Phone Family Announcement" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "Post Writing (aka Finding Mattie)" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "Banyon House Rent Saga" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "Light Orb Video" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "Changing the Locks" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "WTF Natty…" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "I Offered Her A Job…" because TypeError: Cannot read properties of undefined (reading 'split')
Failed: "12-3-22 Random Unfounded Accusations" because TypeError: Cannot read properties of undefined (reading 'split')

Some of these errors are inexcusable. "File names cannot end with a dot or a space." Have you lost your mind? If the note title contains a character that you cannot accept, just remove the motherfucker and maybe note a warning in the log that you had to alter the title! But don't fail over something you can recover from! 

[rant]
I'm not being insulting or randomly complaining because if I were in your shoes, I could and would have done much better than this. You are simpoly not a very good programmer. I mean, this is very basic stuff and it's obvious that you aren't even trying. When you act like this, it gives OSS a bad impression in people's minds that it's written by people who simply don't give a fuck. And to make matters worse, this is an "official" module! Get your shit together, man!
[/rant]

Have you given any thought at all to what a user is supposed to do with all of these failures? What do you expect me to do when I go through and remove the offensive dots, spaces, and colons? Perform a full re-import of everything? Assuming that import even worked in the first place, I highly doubt you're prepared to behave correctly in the event of a re-import. So what then? Are we down to cut-and-paste? I don't know because there isn't any direction offered in this regard because you guys feel like you can toss up errors willy nilly but have no obligatrion after that point. Bullshit! 

Now let's talk about the errors that aren't even true. You say that a title cannot end in a space or a period and it doesn't. What now?

Now let's talk about the errors that are incomprehensible. "TypeError: Cannot read properties of undefined (reading 'split')" What do you honestly expect a user to do with that? I've been a software architect for more than two decades and I don't even know what that means! My best guess is that maybe you lost your connection to the server and it's just throwing some nonsense exception. But this whole thing happened within about 10 minutes from the time I logged in and I assure you that my internet connection is stable, so that doesn't really seem reasonable. I really don't know. But you should and you should catch these exceptions and write something that a reasonably intelligent human being can understand AND DO SOMETHINBG ABOUT in the log. Don't just write, "Fail: Things suck" in the log because there is no obvious course of action a user can take to correct it. You do realize that ALL errors must be correctable, don't you? Well, there's just you and me in this room, buddy boy. Either you fix it or I do, and you're the "expert". So if you cannot fix it, then I need you to tell me what I have to do to fix it,. If your error messages aren't communicating that, then they are wrong and must be changed. Furthermore, there must be a plan for how to import the failed notes once the issue is corrected.

I think your biggest problerm is that you're trying to read the data from Microsoft's servers. Why are you doing that? All of the notes are present on the local filesystem. Either read them from there or have the user export them to JSON or whatever if that's easier for you. But clearly, the way you're doing it is not working.

Before moving on, I also want to offer you some praise for having a log at all. This pervasive trend of not giving the uesr any feedback at all regarding failures is simply deplorable. So thank you for at least implementing a log for me to complain about!

3. Have you never heard of tables? They are these things people use to easily represent data that lends itself to columnar rendering. Imagine if I had a bowl of apples and some where red and some were green. I could document that with a table containing two rows and two columns like this:

Apples:
Color   |   Amount
Red      |  4
Green   |  2

You see how that works? Both OneNote and Obsidian are capable of storing and rendering data in this super-sophisticated format. Your job is to write software that converts from one to the other. DO THAT!!

I'm getting tired of writing this and my vitriol reserves are nearly depleted, so at least this has served that purpose. I figure the odds of anyone reading this far into this report are about zero percent because if you cared that much, we wouldn't even be here in the first place. As for me, I'm off to go leave you the one-star review on the app store that you rightly deserve.

**Comment by kepano** [comment]
Please respect the [community code of conduct](https://help.obsidian.md/Obsidian/Community+code+of+conduct).

**Comment by issaqua** [comment]
Whilst the original bug report might have been a bit blunt (cranky old person - I can relate ;), but I have the same issues.  Were these issues fixed?  (I've not been using the importer because it is non-functional - it only picks up 20 or so items from my many thousands of notes.)

**Comment by issaqua** [comment]
And last, but not least, it also doesn't handle the HTTP return/status code 429 gracefully - throttling.  That leads to the errors previous, etc..

**Comment by kepano** [comment]
Search the OneNote tag and open individual issues where relevant

**Comment by issaqua** [comment]
damn, if that's the response I wont bother logging any more issues and I'll just uninstall the plugin.  Feel free to close from my perspective.
