### ISSUE TITLE
Importer should tell me which notes failed to import

### ISSUE THREAD

**Issue by semiswirl** [obsidianmd/obsidian-importer#29]
Use case or problem
I was importing a batch of ~3k notes from Evernote. 18 notes failed, but I couldn’t tell which ones.

Proposed solution
Provide the title for each note that failed to import.

Current workaround (optional)
If you open the console before running the import and filter by “failed to convert”, you can see the notes that failed. If you DON’T open it before running, then it seems to only retain the last 100 or so notes imported, which may or may not include those that failed.

**Comment by ericaxu** [comment]
Should be fixed in 1.0.4!
