### ISSUE TITLE
[Evernote] Improvements suggestions for Importer

### ISSUE THREAD

**Issue by AltoRetrato** [obsidianmd/obsidian-importer#290]
For users with thousands of notes in another program (e.g., Evernote) who want to move to Obsidian, being able to import those notes without losing data (including formatting) and without having to manually compare all imported notes and fix every import issue is a very important feature.

Here are a few suggestions to improve the process of importing notes from Evernote into Obsidian, based on my own recent experience:

## Change Note titles

**Obsidian note titles can't have the special characters** `* " \ / < > : | ?`  because a note title also serves as its file name. Emoji in file names might not be supported as well (e.g., when using Dropbox to sync the Obsidian vault). Currently, the Importer just removes these special characters, but better alternatives would be:

1. Allow the user to choose a custom replacement character or string (e.g., `-` `_` ` -- `) for these special characters, and, if the user wants, replace emojis as well.
2. Replace the special characters with similar-looking Unicode or ASCII characters, such as ✱ ✲ ＊ ⁎ ※ ' “ ” ⧵ ∖ ＼ ∕ ⁄ ‹ ⟨ 〈 ❮ › ⟩ 〉 ❯ ∶ ꞉ ː ։ ∣ ¦ ┃ ǀ ｜ ？ 

(FWIW, I tried importing the notes with Yarle, which has a "Global search and replace (regexp) in note title and content" feature, but it didn't work for me.)

## Customize PDF Links / Previews

**Notes with many PDF files can become very unresponsive**. In Evernote, you can choose whether a PDF file is shown as "Title" (aka "attachment"), which is equivalent to showing only the PDF title as a link in Obsidian; "Single page" (aka "pdf-pageByPage"); or "All pages" (aka "pdf-full"), with the last two being equivalent to showing a preview of the file. Currently, this information is not utilized during importing, so imported notes with PDFs have all them with preview enabled. This might break formatting (especially in tables) and cause performance issues on notes with many PDFs, requiring a lot of manual editing by users to fix. I'd suggest:

1. Ask the user if they want the PDF (and possibly other types of documents) to appear as a link (e.g., `[[path/to/test.pdf|test.pdf]]`), as a preview (`![[path/to/test.pdf|test.pdf]]`), or as set in the .enex files.

The PDF display setting appears in .enex files like this:
```xml
<en-media style="--en-viewAs:attachment;" hash="..." type="application/pdf" />
<en-media style="--en-viewAs:pdf-pageByPage;" hash="..." type="application/pdf" />
<en-media style="--en-viewAs:pdf-full;" hash="..." type="application/pdf" />
```

## Allow Longer File Names

**I noticed that some long file names are shortened after being imported**, but often there is important information in file names that users do not want removed. I understand that there are file name length limitations on many systems, but it seems the longest _total_ path for a file after importing was only 160 characters - yet I can easily create much longer file names. Ideally, the Importer plugin would ask me to rename any file if necessary, or at least inform me when it is automatically shortening file names.

## Log Changes and Issues While Importing

**Create a log listing all notes that were changed** during import, how they were modified (and why), and any issues encountered (e.g., Evernote supports merged cells in tables, but this is lost when importing into Obsidian). With this information, the user can decide if they want to manually review and edit a specific set of notes.

I have already created issues #286 (regarding incorrect "Last modified" dates) and #287 (image size not being preserved after importing), which I consider more bugs than "improvements".

**Comment by kepano** [comment]
Thanks for sharing your feedback. These should be split into separate issues, and not all of them are specific to Evernote.

**Comment by AltoRetrato** [comment]
> Thanks for sharing your feedback. These should be split into separate issues, and not all of them are specific to Evernote.

True! I'll do that.

**Comment by AltoRetrato** [comment]
Done!
