### ISSUE TITLE
Importing from Bear backup crashes Obsidian 

### ISSUE THREAD

**Issue by ilium007** [obsidianmd/obsidian-importer#297]
After using the importer to open a Bear backup (as per https://help.obsidian.md/import/bear) the app initially seems to do something (black box with some stats) but very quickly goes to a grey box where it hangs.

<img width="823" alt="image" src="https://github.com/user-attachments/assets/6dce2ea2-8594-4502-9746-2435c9ad5dc4">

<img width="396" alt="image" src="https://github.com/user-attachments/assets/1b208457-9f80-4167-89ca-03040ef0c259">

**Comment by tgrosinger** [comment]
Hello,
Can you please attempt the import again in a fresh vault? Maybe test again with a different Bear export?

If you are able to reproduce the issue, please provide us with more information about your Bear export so we can track down the issue.

Thank you.

**Comment by ilium007** [comment]
I have tried more than 5 times with different data sets. The last resulted in another issue I have raised re. duplicate image corruption on import. At this stage in think I'll just stick with Bear.

**Comment by tgrosinger** [comment]
Hi @ilium007, there have been some fixes recently for handling attachment importing from Bear exports. Please let us know if these resolve the issue you were running into. Thanks!
