### ISSUE TITLE
Notes are skipped on import due to attachment name duplicates

### ISSUE THREAD

**Issue by ilium007** [obsidianmd/obsidian-importer#298]
This has been mentioned before in https://github.com/obsidianmd/obsidian-importer/issues/229 and https://github.com/obsidianmd/obsidian-importer/pull/231

Notes are skipped on import due to attachment name duplication (this is a subset of thousands of notes I wanted to migrate):

![image](https://github.com/user-attachments/assets/49e4965a-794c-4ab9-a601-733780369bc9)

On some notes that have been imported images have been swapped out with other images because filenames in attachments from Bear are the same.

**Comment by ilium007** [comment]
Another report here: https://github.com/obsidianmd/obsidian-importer/issues/181

**Comment by lishid** [comment]
Seems to have been closed multiple times as duplicates. There's an active PR that has been reviewed but the author has since disappeared. Let me see if we can make some more progress on it.

Here's the active PR: https://github.com/obsidianmd/obsidian-importer/pull/231

**Comment by jspv** [comment]
Still very much a problem with 1.6.5 importing from OneNote

**Comment by tgrosinger** [comment]
Thanks for reporting this. Looks like the fix we put in was specific to the Bear format. I'll look into a more generic fix.

**Comment by tgrosinger** [comment]
@jspv, would you mind testing if this update fixes the OneNote importer duplicate attachment names issue for you?

1. Download this zip: [main.zip](https://github.com/user-attachments/files/17284400/main.zip)
2. Unzip the file.
3. Open your Obsidian vault, replace <your-vault>/.obsidian/plugins/obsidian-importer/main.js with this file.
4. Close and reopen Obsidian.

**Comment by tgrosinger** [comment]
This should be resolved in 1.6.8. Please let us know if it is not.
