### ISSUE TITLE
Filenames are urlencoded when import from Notion

### ISSUE THREAD

**Issue by and7ey** [obsidianmd/obsidian-importer#303]
Here is an example how some file names are imported:

<img width="346" alt="image" src="https://github.com/user-attachments/assets/e751057b-2ace-43a3-b3a4-a61bab75f997">

Here is an example of full filename:
`%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE_%D0%BF%D0%BE_%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8E_DK103M(W)(-4G)`

**Comment by tgrosinger** [comment]
Would it be possible for you to provide us with a Notion export zip file that we could use to help test and resolve this issue? Thank you!

**Comment by and7ey** [comment]
@tgrosinger I can not share the export zip since it contains confidential info. 
But I can give you more details.

Here is the screenshot from Notion exported html:
<img width="1639" alt="image" src="https://github.com/user-attachments/assets/c4ba87ed-1ad2-4937-94d0-5ea4078ecdfe">
the file is referenced somewhere here I think:
`<figure id="8d1a494d-0a00-4958-b879-876fe051cf94"><div class="source"><a href="%D0%94%D0%BE%D0%BC%D0%BE%D1%84%D0%BE%D0%BD%20Beward%2016aaf973752a4cc89313e48964bc76a0/%25D0%25A0%25D1%2583%25D0%25BA%25D0%25BE%25D0%25B2%25D0%25BE%25D0%25B4%25D1%2581%25D1%2582%25D0%25B2%25D0%25BE_%25D0%25BF%25D0%25BE_%25D0%25BF%25D0%25BE%25D0%25B4%25D0%25BA%25D0%25BB%25D1%258E%25D1%2587%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258E_DK103M(W)(-4G).pdf">Руководство по подключению DK103M(W)(-4G).pdf</a></div></figure>`

The filename is actually URL encoded:
<img width="971" alt="image" src="https://github.com/user-attachments/assets/e22e57a9-0f63-4d86-956c-c432098e5c86">

**Comment by felciabatta** [comment]
Hi @and7ey, was `Руководство по подключению DK103M(W)(-4G).pdf` the original filename of the PDF stored in your Notion workspace?

If so, then this means Notion is responsible for encoding the filename on export, and perhaps we can decode this with Importer...

**Comment by and7ey** [comment]
The decoded filename looks Ok

**Comment by felciabatta** [comment]
I just tested this in my Notion workspace and can confirm the same thing happens when exporting.

Will have a look in decoding back into the original characters — the challenge will be updating this across the Vault for all references to the file.

**Comment by felciabatta** [comment]
> The filename is actually URL encoded:

It's actually even worse than that; this is the component of the `href` _referring_ to the filename itself (_not_ the full path):

`
%25D0%25A0%25D1%2583%25D0%25BA%25D0%25BE%25D0%25B2%25D0%25BE%25D0%25B4%25D1%2581%25D1%2582%25D0%25B2%25D0%25BE_%25D0%25BF%25D0%25BE_%25D0%25BF%25D0%25BE%25D0%25B4%25D0%25BA%25D0%25BB%25D1%258E%25D1%2587%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258E_DK103M(W)(-4G).pdf
`

and compare this to the URL-encoded filename:

`
%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE_%D0%BF%D0%BE_%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8E_DK103M(W)(-4G).pdf
`

They're not the same — the `href` is a **double-encoded** version of the original filename: 

`Руководство по подключению DK103M(W)(-4G).pdf` — **but not quite** — when you decode the `href` you get: 

`Руководство_по_подключению_DK103M(W)(-4G).pdf` — so it also replaces spaces with underscores!

This leads me to believe this is actually a bug with Notion's export utility: the encoding should only be required for the `href`, not the actual file itself — it makes no sense to double-encode like this. 😭

**Comment by and7ey** [comment]
What if we follow the MS Excel approach when importing CSV file - it shows the file content, suggests the encoding and asks if user would like to change it. What if we do the same? Single encoding, double encoding?

**Comment by felciabatta** [comment]
I think it's probably simpler to default to decoding the filenames — we know how Notion encodes them so we can just apply the same decoder across the board.

For filenames that aren't encoded in the first place, applying the URL decoder should leave them unmodified anyway — although in theory someone _could_ intentionally have `%XX` strings in their filename...

**Comment by felciabatta** [comment]
@and7ey turned out to be a nice and simple fix, see my PR #338.

**Comment by and7ey** [comment]
@felciabatta many thanks! Should I re-import the Notion database? Or is there any better approach?

**Comment by felciabatta** [comment]
> @felciabatta many thanks! Should I re-import the Notion database? Or is there any better approach?

The update is still under review, but when released:
- if you have a lot of files affected by the issue, then I imagine re-importing the Notion workspace would be easiest, since Importer will decode automatically
- if it's just a few files, then I guess you could just rename them manually using an online [url decoder](https://meyerweb.com/eric/tools/dencoder/) or in JS
- if you imported the workspace a while ago and have been modifying the imported notes in Obsidian, then obviously the re-imported notes won't match the modified versions...

**Comment by and7ey** [comment]
I've imported the workspace long time ago and added/modified a lot of notes and I have many-many files :). Looks like I'll have to write a plugin to rename the files :).

**Comment by felciabatta** [comment]
> I've imported the workspace long time ago and added/modified a lot of notes and I have many-many files :). Looks like I'll have to write a plugin to rename the files :).

Aha, good luck! `decodeURIComponent` in JS should do the trick; then search and replace for all internal links to your files: _eg_ `[[url%20filename.pdf]]`.
