### ISSUE TITLE
Bear importer only imports attachments

### ISSUE THREAD

**Issue by jezper** [obsidianmd/obsidian-importer#304]
Any issue with the Bear importer or is this a user error on my behalf?

Trying to import a .bear2bk into a fresh Vault and only getting the attachments imported, no notes. I get two empty folders for trash and archive, but nothing in there either.

**Comment by rtud** [comment]
Seeing the same behavior on my end.

**Comment by tgrosinger** [comment]
Hello, thanks for reporting this issue. I've got a couple exports from Bear that we use for testing, and both are importing the notes as expected. Would one of you be able to share an export that reproduces this issue that I can use for fixing this issue?

**Comment by tgrosinger** [comment]
Could you please also let us know what operating system you are using?

**Comment by HybridRbt** [comment]
I am on macOS 15.0. My Bear is on v2.3.3. I will see if I can create a shareable backup of the notes.

**Comment by rtud** [comment]
System 1: macOS 15.0, Bear 2.3.3, Obsidian 1.6.7, Obsidian Importer Plugin 1.6.5
System 2: Arch Linux via LTS kernel, Obsidian 1.6.7-1 via pacman, exported Bear notes in `.bear2bk` format from Bear 2.3.3

Thank you!

**Comment by tgrosinger** [comment]
I have made some changes to the Bear importer to improve how we handle attachments and duplicate file paths (#305). Would any of you be willing to give it a test and report if it resolves this issue?

1. Download this zip: [main.zip](https://github.com/user-attachments/files/17247481/main.zip)
2. Unzip the file.
3. Open your Obsidian vault, replace `<your-vault>/.obsidian/plugins/obsidian-importer/main.js` with this file.
4. Close and reopen Obsidian.

Thank you!

**Comment by jezper** [comment]
@tgrosinger 

That did the trick (at least for me!)

![image](https://github.com/user-attachments/assets/836749eb-b8b2-476d-812d-d0a2b2ffa4c2)

**Comment by HybridRbt** [comment]
I can also confirm that the new main.js file has fixed it. 
<img width="563" alt="截屏2024-10-04 下午11 47 36" src="https://github.com/user-attachments/assets/31fb255a-819f-4e9c-b2c5-b9d31e61ca64">

**Comment by tgrosinger** [comment]
This problem should be resolved in the latest release. Thanks for helping test!
