### ISSUE TITLE
Onenote Attachments aren't imported if Filename starts with Number

### ISSUE THREAD

**Issue by keichhorn** [obsidianmd/obsidian-importer#320]
[ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer...Failed: "Exported image 20241115095419-5.jpeg" because TypeError 
[ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer...Failed: "Exported image 20241115095419-6.jpeg" because TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer...

The User doesn't have the ability to rename Attachments. 
Attachments get the Name "20241115..." in Onenote, if the user adds a picture through the mobile Version of Onenote.

I don't care if the attachments are renamed as long as they are imported

**Comment by tgrosinger** [comment]
Hello,
Can you please confirm that this is still occurring after making sure you are running the latest version of the Importer plugin?

I've been testing with different ways of attaching images, including from the android Onenote app, but the attachments are always renamed to "Exported image 20241216..." when they are downloaded and embedded in an Obsidian note.

**Comment by keichhorn** [comment]
Wow, you guys are amazing!

I have just installed Version 1.6.15 of the Importer and started the Onenote Import again.
It works flawlessly now! All Pictures are correctly imported without errors.

Thank You!
