### ISSUE TITLE
Import not Successful because of File Name

### ISSUE THREAD

**Issue by keichhorn** [obsidianmd/obsidian-importer#321]
Failed: "Zus: Betriebswirtschaftliche Grundlagen Zusammenfassung" because Error: File name cannot contain any of the following characters: * " \ / < > : | ?

I've already renamed lots of Notes. But some of them still slip through.
Problem: The Note in Question is not imported into Obsidian + If too many Notes failed to Convert, the Importer just stops (and does not import the remaining Notes)

I suggest, that if a filename has invalid characters, that the characters are replaced with a standard symbol (like ".").

This way, everything is converted. And the User has to check anyway, if his/her notes have converted completely and are still usable

**Comment by tgrosinger** [comment]
I'm going to merge this with #291 since it looks very similar.
