### ISSUE TITLE
[Notion] Inline equation with leading or tailing spaces do not get imported correctly

### ISSUE THREAD

**Issue by tooxo** [obsidianmd/obsidian-importer#330]
In Notion leading or tailing spaces do not change anything in the appearance of the equation. If I import an equation like this into Obsidian the inline math breaks. 

Notion:
![Notion](https://github.com/user-attachments/assets/d8136405-598c-4053-aa08-236fba01f734)

Obsidian:
![Obsidian](https://github.com/user-attachments/assets/b000d634-5c21-4f71-8e49-8e7e8688ebde)

@felciabatta (I hope the mention is okay, as you successfully solved the problem I had before :) )

Example Project: 
[1b19d8ae-4664-40db-bd85-608867c8bb80_Export-d70d856c-b32d-4af3-a1db-44944a1654cb.zip](https://github.com/user-attachments/files/18037450/1b19d8ae-4664-40db-bd85-608867c8bb80_Export-d70d856c-b32d-4af3-a1db-44944a1654cb.zip)

**Comment by felciabatta** [comment]
> @felciabatta (I hope the mention is okay, as you successfully solved the problem I had before :) )

No worries at all, I'll have a look into it! 
I'm familiar with the source now, so should be able to locate the issue :)

**Comment by felciabatta** [comment]
@tooxo I have resolved this; will submit a pull request soon :)

**Comment by tgrosinger** [comment]
Fixed in #331
