### ISSUE TITLE
Detailed import log and progress bar - $500

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#35]
Allow users to see a detailed log, similar to Sync log with list of every file. This would be combined with the progress meter into a new screen that  is displayed while the import is running.

## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $500 USD
**Timeframe:** 7 days

## Requirements

- [ ] Should be generic and compatible with existing/future converters
- [ ] Import progress modal should replace the "Import data" modal once import begins
- [ ] Progress meter
  - [ ] Number of remaining files (if available)
  - [ ] Number of skipped files
  - [ ] Number of failed files
  - [ ] Number of imported files
  - [ ] Progress bar should use total count of files if available, otherwise use an indefinite cycling progress bar  
- [ ] List of all files with states
  - [ ] Imported — timestamp, original file name, location of the new file (text color `--text-muted`)
  - [ ] Failed — timestamp, original file name, error message (text color `--text-warning`)
  - [ ] Skipped — timestamp, original file name, skipped message (text color: `--text-error`)
- [ ] Toggle "errors only" to only show failed and skipped files

## Reference

Mockup modified from current Sync log

<img width="979" alt="Screenshot 2023-07-31 at 2 06 47 PM" src="https://github.com/obsidianmd/obsidian-importer/assets/10565871/d27c17f5-d460-4213-b0e5-4e4a561d45eb">

Progress bar from [Google Keep Import plugin](https://github.com/daledesilva/obsidian_google-keep-import) by @daledesilva

<img width="979" alt="Screenshot 2023-07-31 at 2 06 47 PM" src="https://github.com/daledesilva/obsidian_google-keep-import/raw/main/docs/media/progress-preview.gif">

**Comment by daledesilva** [comment]
I won't create a new issue incase you want to role it into this one, but I would suggest that a drag and drop and better summary section before import would be nice too. Currently, if you browse and select 1000s of files, you have to scroll a long way down to find the import button.

Here's an example from the same plugin
<img width="655" alt="Screenshot 2023-08-01 at 11 19 47 am" src="https://github.com/obsidianmd/obsidian-importer/assets/18710973/e70a08e5-ef7f-4d61-99ac-c18115f90e20">

**Comment by Quorafind** [comment]
I would like to apply for this task. I have extensive experience in building Obsidian plugins. In addition, I also possess basic UI design skills.

The Obsidian plugins I've built include Surfing, Obsidian-Memos, Obsidian Canvas Mindmap, and Obsidian Tasks Progressbar.I believe I am well-suited for this task. You can find the plugins above from my repos: https://github.com/Quorafind?tab=repositories&q=obsidian&type=&language=&sort=

**Comment by polyipseity** [comment]
I think it would also be nice if there is a separate count for attachments.

**Comment by kepano** [comment]
> I won't create a new issue incase you want to role it into this one, but I would suggest that a drag and drop and better summary section before import would be nice too. Currently, if you browse and select 1000s of files, you have to scroll a long way down to find the import button.

There is a related issue #20 that I think would be a better fit for that. The drag and drop behavior should happen on the previous step (before import log)

**Comment by arthurtyukayev** [comment]
I wouldn't mind taking this claiming this one if it hasn't already been claimed. I've got experience working with web dev and electron.

I just finished (in review currently), an importer for Bear's `bear2bk`.
