### ISSUE TITLE
Plugin does not show in Commuity Plugins left pane

### ISSUE THREAD

**Issue by egauthier** [obsidianmd/obsidian-importer#36]
Obsidian: 1.4.2
Importer: 1.04
Vault: Sandbox
Mac OS Ventura

This is odd.  Importer shows when browsing plugins, it shows in the list of installed plugins, but it doesn't show in the left pane of the settings under `Community Plugins`

I opened the sandbox vault. Installed and enabled both Importer and Calendar.  Calendar is shown in the left pane of the settings modal under `Community Plugins` but Importer is not.

![Screenshot 2023-07-31 at 2 25 15 PM](https://github.com/obsidianmd/obsidian-importer/assets/880143/f8dd83d5-3e5e-48a5-a5ac-4795664ff9d6)

**Comment by kepano** [comment]
This is expected. Take a look at instructions in the readme. You can open importer via the ribbon menu or command palette.

**Comment by egauthier** [comment]
OK, sorry for the invalid issue.  I never really understood what that left pane was for anyhow.  Now I get it, invocation.

The hotkeys for Importer work for me!!

Thanks!
