### ISSUE TITLE
Support for Obsidian mobile apps

### ISSUE THREAD

**Issue by LeslyeCream** [obsidianmd/obsidian-importer#4]
Is it possible?

**Comment by lishid** [comment]
Unfortunately since it currently makes heavy use of NodeJS APIs, the plugin will not run on mobile - hopefully we can rework it to strip out the node API usage later on.

**Comment by daledesilva** [comment]
This is interesting.
When I first started working on the [Google Keep Import ticket](https://github.com/obsidianmd/obsidian-importer/issues/12) I noticed that the references to files being imported worked differently to my plugin and suspected it might create this limitations.

I just confirmed that using my iPad I was able to download a Google export, unzip it, and then using my original Google Import Plugin I was able to import it into Obsidian without issues. All on my iPad. The difference is that in that plugin I really on a standard HTML input component to allow the user to select or drop the files.

```js
this.uploadInput = dropFrameText.createEl('input', { 
	type: 'file',
	attr: {
		'multiple': true,
		'id': 'gki_file-input',
	}
})
```

A reference to that HTML component, allows fetching a FileList. Here I use it in a listener for any changes to the component.

```js
this.uploadInput.addEventListener('change', () => {
	this.addToFilesBacklog( Object.values(this.uploadInput.files as FileList) );
});
```
The **FileList** is already a **reference to the files.** This is different to the **obsidian-importer**, which passes a list of **paths**. This means that the obsidian importer requires FS to use those paths to access the files. And FS is not available on mobile.

I'd suggest that this fundamental change should be prioritised. I would guess that lots of potential users likely only have mobiles or tablets, and now would be the time to change this before too many other import formats are added.

**Comment by lishid** [comment]
> I'd suggest that this fundamental change should be prioritised. I would guess that lots of potential users likely only have mobiles or tablets, and now would be the time to change this before too many other import formats are added.

Thank you, I will look into this today. The goal is to create a shared/common API that is agnostic to nodejs vs capacitor/web.

**Comment by lishid** [comment]
I have restructured the codebase to support mobile. I haven't tested it though, let me know if anyone can give it a quick whirl
