### ISSUE TITLE
Import TextBundle format

### ISSUE THREAD

**Issue by arthurtyukayev** [obsidianmd/obsidian-importer#43]
.textbundle file/folder format

http://textbundle.org/

It's used by a bunch of different applications, the format is quite simple.

Generally a single .textbundle would contain a single markdown file and a folder of any assets that file includes.

**Comment by tgrosinger** [comment]
PR #63 adds this format.

**Comment by Kullenej** [comment]
When I export a mindmap from Mindnode as a markdown with images, it gets exported as a .textbundle. When I try to import it into Obsidian with the importer-plugin, I can't seem to choose the .textbundle-file. It is greyed out in the pop-up. See images: 

<img width="584" height="365" alt="Image" src="https://github.com/user-attachments/assets/e4ee96d4-16d0-423c-8ecb-09e6a41b3075" />

<img width="839" height="658" alt="Image" src="https://github.com/user-attachments/assets/a32dd240-b0d2-4c0b-9f51-32b32a19a85d" />
