### ISSUE TITLE
Dev: fails tsc

### ISSUE THREAD

**Issue by joshuatazrein** [obsidianmd/obsidian-importer#46]
I get this error when trying to build:

```
> obsidian-importer@1.0.1 build
> tsc -noEmit -skipLibCheck && node esbuild.config.mjs production

error TS2688: Cannot find type definition file for 'node 2'.
  The file is in the program because:
    Entry point for implicit type library 'node 2'


Found 1 error.
```

**Comment by lishid** [comment]
I can't seem to reproduce that, are you running this on clean master?

**Comment by joshuatazrein** [comment]
> I can't seem to reproduce that, are you running this on clean master?

This is with an up-to-date master, but it's in my fork to the Notion importer. Let me close this issue and open a new one there.
