### ISSUE TITLE
Images in an html file are missed

### ISSUE THREAD

**Issue by notuntoward** [obsidianmd/obsidian-importer#52]
If I look at the attached html file in a web browser, it looks like this:

<img width="813" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/3851891/6acf700f-151e-4b54-aaac-61cc103b3174">

This was exported from evernote, and it looks pretty much the same there.

However, when I import into into obsidian using the obsidian importer plugin, it looks like this:

<img width="513" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/3851891/c56c455d-a33d-46b2-ab1f-d6e71a7890c3">

[Evernote_is_really_html.txt](https://github.com/obsidianmd/obsidian-importer/files/12292546/Evernote_is_really_html.txt)

**Comment by lishid** [comment]
What importer are you using to import this file and can you send the resources folder as well? The HTML file just has a `<img src="Evernote.enex_files/Image.jpg" ` so it must have been somewhere nearby the HTML file?

**Comment by ericaxu** [comment]
To keep things tidy, we're going to close issues that we don't hear back after a month of inactivity.

Feel free to tell us to re-open it when you're ready to reply and we'll reopen the issue right away. Thanks for your understanding!
