### ISSUE TITLE
Import from Evernote: texts are missing

### ISSUE THREAD

**Issue by caiy0233** [obsidianmd/obsidian-importer#53]
I tried to import from a .enex file which contains 12 notes but only 1 note was imported completedly. In the rest 11 notes, only the images in them are imported in _resources folders but the texts are missing.  

![image](https://github.com/obsidianmd/obsidian-importer/assets/43733133/8ef92060-db67-41cd-aa73-b123770bf343)

**Comment by ericaxu** [comment]
Please provide the minimal enex files for us to reproduce it.

It would be nicer to say what you expect to see and what you see instead. Thanks!

**Comment by caiy0233** [comment]
Hi, the attachment is the minimal enex file, which is generated from 2 notes from Evernote. Both of the 2 notes contain texts.

However, after I imported from the enex file to obsidian, only the images of the first note was imported and the text of the first note was missing. The second note was imported completedly. That's what I saw.






What I expected to see is 2 imported notes just like what they look like in Evernote, instead of 1 note and 1 image folder with text missing.
Thanks a lot!&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obsidianmd/obsidian-importer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 凌晨2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obsidianmd/obsidian-importer] Import from Evernote: texts are missing (Issue #53)





 
Please provide the minimal enex files for us to reproduce it.
 
It would be nicer to say what you expect to see and what you see instead. Thanks!

**Comment by kepano** [comment]
If this issue is still occurring please reopen with a sample .enex to reproduce
