### ISSUE TITLE
Save Parent in Subfolder option for Notion import not working in 1.10

### ISSUE THREAD

**Issue by Satanniel** [obsidianmd/obsidian-importer#58]
Despite "Save Parent in Subfolder" being ticked the parent notes still were saved level above. This used to work on the Notion's branch, since I've tested it extensively (and suggested that option in the first place).

**Comment by kepano** [comment]
@joshuatazrein I was able to reproduce this as well

**Comment by joshuatazrein** [comment]
This was working before the migration, let me see what's changed.

**Comment by joshuatazrein** [comment]
I have no idea why, but it's because the setting appears to be set as `false` by default. I don't see any reason why in the code, it should be `true`.

**Comment by lishid** [comment]
Fixed - it's a special case with javascript initializers - init is ran by the parent constructor, and the initializer (`field = false`) causes it to revert.
