### ISSUE TITLE
Notion import checkboxes bug

### ISSUE THREAD

**Issue by OsmarJoseph** [obsidianmd/obsidian-importer#62]
When importing notion `.zip` into obsidian, notion checkboxes are being turned into simple `list` items.

**Comment by ericaxu** [comment]
@joshuatazrein Can you take a look and see if you could repro it? Thanks!

**Comment by Satanniel** [comment]
For me checkboxes imported properly.
![image](https://github.com/obsidianmd/obsidian-importer/assets/8254867/62dfab5b-7aa7-44e2-85b1-f2eeb0967801)
![image](https://github.com/obsidianmd/obsidian-importer/assets/8254867/021bf3c1-5136-4da3-b938-1bece1d80606)

**Comment by joshuatazrein** [comment]
> When importing notion `.zip` into obsidian, notion checkboxes are being turned into simple `list` items.

In order to fix this can you upload the problematic file, both its original `.html` and the converted `.md?`

**Comment by OsmarJoseph** [comment]
sure, here is the html example:
[example c2f20d00f3414fe8a0a50bf16013af1d.html.zip](https://github.com/obsidianmd/obsidian-importer/files/12329508/example.c2f20d00f3414fe8a0a50bf16013af1d.html.zip)

the output
```
- todo example
```

**Comment by joshuatazrein** [comment]
Ahh, I see what you mean. I'll add a parser option for this.

**Comment by joshuatazrein** [comment]
Simple update needed: 

```
const addCheckboxes = (body: HTMLElement) => {
	const checkboxOn = body.findAll('.checkbox.checkbox-on')
	checkboxOn.forEach(el => el.setText('[x] '))
	const checkboxOff = body.findAll('.checkbox.checkbox-off')
	checkboxOff.forEach(el => el.setText('[ ] '))
}
```
