### ISSUE TITLE
Notion import cyrillic in file names problem and mode

### ISSUE THREAD

**Issue by Sinled** [obsidianmd/obsidian-importer#66]
Hey, i am trying new version with notion import, and encountered two problems

1. It breaks file and folder names with cyrillic

<img width="240" alt="Screenshot 2023-08-12 at 21 23 16" src="https://github.com/obsidianmd/obsidian-importer/assets/1402135/3d715295-e0da-497e-aa9b-ce3c58fcfda1">

2. It seems there is a problem when you make partial export in notion - it includes referenced pages several times, so there might be a chance of file name collision, import just stuck with error 

```
app.js:1 Uncaught (in promise) Error: Folder already exists.
    at t.<anonymous> (app.js:1:1024123)
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
```

it can be solved by manually removing them from archive though

**Comment by joshuatazrein** [comment]
Can you upload a sample exported page for testing and debugging? Just upload a .zip to the issue.

**Comment by Sinled** [comment]
Here is an minimal example with Cyrillic problem, but i couldn't reproduce collision issue on test pages
[notion_test_minimal.zip](https://github.com/obsidianmd/obsidian-importer/files/12329210/notion_test_minimal.zip)

> The recommendation is to import everything in one go so the links aren't mixed up

thanks, i'll try this

**Comment by joshuatazrein** [comment]
This export is the `markdown` export. In order for this to work you have to use the `HTML` export from Notion.

**Comment by Sinled** [comment]
Oh i see, there is nothing in import window suggesting it, only link where it can be found. I'll try and check if html export doesn't have encoding problem. 

But probably for better user experience mention of html export should be on the import window.
