### ISSUE TITLE
When using Bear import, header will be imported twice

### ISSUE THREAD

**Issue by jmrauen** [obsidianmd/obsidian-importer#71]
In Bear textbundle-format the first line will be used as the filename (correct) but it will be inserted into the obsidian note (wrong). 
Please cut the first line, because I get the header twice. Thanx!

![image](https://github.com/obsidianmd/obsidian-importer/assets/23209835/9b063b33-a53f-4557-b57e-8ecdaf0bdeda)

**Comment by lishid** [comment]
Just to make sure I understand, the notes themselves have a heading that's identical from the note name, right? You're suggesting we should cut off the first heading from the note since we already show the file name in the UI.

**Comment by jmrauen** [comment]
Yes, that's right. You only to cut off the first heading from the note.

**Comment by timsearle** [comment]
+1 on this! Would agree that this is a bug rather than enhancement. The top line of a Bear note is always the title of a note, whereas the Importer is treating the top-line as the title and then repeating the top line in the note contents.
