### ISSUE TITLE
Import from iA Writer

### ISSUE THREAD

**Issue by davebhc71** [obsidianmd/obsidian-importer#74]
As the Title asks, please include a feature to import Notes from iAWriter! Thank you!!!

**Comment by kepano** [comment]
As far as I know iA Writer uses regular Markdown files. What would make this different from #23 ?

See also https://help.obsidian.md/import/markdown

**Comment by davebhc71** [comment]
Probably nothing! Actually, unless you know a reason not to, I can point iA Writer to an Obsidian folder and create files that Obsidian can also read/edit, which is the best of both worlds for my workflow.

**Comment by ericaxu** [comment]
Closing as duplicate of #23
