### ISSUE TITLE
Import from Notion fails

### ISSUE THREAD

**Issue by AmusingMallard** [obsidianmd/obsidian-importer#77]
I have followed the documentation [here](https://help.obsidian.md/import/notion) but the import fails. After starting the import it quickly tallies up the remaining files to be imported and then the "Done" button shows up. No files are imported. In the developer tools console the following error message is shown: 
![image](https://github.com/obsidianmd/obsidian-importer/assets/23269655/3e5f94a4-399c-4869-b982-dfc601d3900f)

Import dialog box:
![image](https://github.com/obsidianmd/obsidian-importer/assets/23269655/3492bc5f-d95c-4d80-b10a-b360445e0e17)

Not sure if this is related to #61. The .zip I'm trying to import is only around 600 MB and the symptoms seem different.

**Comment by lishid** [comment]
Do you have a zip file within your zip file that is an attachment? I think that message seems to say that it ran into a broken zip file.

**Comment by AmusingMallard** [comment]
> Do you have a zip file within your zip file that is an attachment? I think that message seems to say that it ran into a broken zip file.

Not sure if I understand correctly, but the zip I got from Notion has another zip file inside it. I've tried extracting it and importing the nested zip, but I get the same issue. Is this a botched export from Notion?

**Comment by AmusingMallard** [comment]
That seems to have been the issue. I had two zip files that were added as attachments to notes in Notion. I unzipped the whole export, removed the two zip files and zipped the export again. This time the import worked fine. 

Maybe a check could be implemented in the importer so that if the importer finds any nested zip files you'll get a more descriptive actual error message in the UI?

**Comment by lishid** [comment]
Can you show me what those attachment file names look like?

**Comment by AmusingMallard** [comment]
These are the two files I removed from the export: 
![image](https://github.com/obsidianmd/obsidian-importer/assets/23269655/3e6d222c-a750-4a03-b137-b7bd9b38876d)

**Comment by lishid** [comment]
Ah ok, were they named like that in the package? Do you know what path they existed within the zip file? (I'm trying to figure out how we should detect if a zip is an attachment vs a zip that is a nested export zip)

Currently I think the most reasonable thing is to check if the zip is in the root of the parent zip - seems like Notion put the nested zips at the top level but attachments go into a subfolder.

**Comment by AmusingMallard** [comment]
Yes they were named the same.
This is an extract of the folder structure:
```
├── <guid>_Export-<guid-2>.zip <- this is the file I downloaded after exporting from Notion
│   ├── Export-<guid-2>-Part-1.zip
│   │   ├── Export-<guid-2>
│   │   │   ├── <some-notes>.html
│   │   │   ├── <some-databases>.csv
│   │   │   ├── <some-folder>
│   │   │   │   ├── <some-notes>.html
│   │   │   │   ├── <some-databases>.csv
│   │   │   │   ├── <some-folder>
│   │   │   │   │   ├── <some-notes>.html
│   │   │   │   │   ├── <some-databases>.csv
│   │   │   │   │   └── <some-file>.zip <- zip file causing problems
```
As far as I can understand, any zip file contained inside the folder named `Export-<guid2>` is an attachment and not a nested export zip. I think if you add an attachment to a note in the root folder, it would be exported as a folder containing the note in an html file and the attachment in whatever file format the attachment is in.

**Comment by lishid** [comment]
Thanks for the nice diagram! I understand now. I've added a check to only look into zips at the root of the export, which should solve this case, but it might also be a good idea to look for the word "export" in the name.

**Comment by AmusingMallard** [comment]
I did some testing. I created a new workspace. So it only contained the demo content that is generated by Notion. I added a small .zip file to an empty note in the root folder containing only the .zip file. 

Again, it created the same two level nested zip file as before, but as you can see from the screenshot, the note containing the zip file becomes an html file in the root folder, while the zip file attached to that note ends up in a folder that is named the same as the html file. So there should be no risk of having any zip files (or any non html/csv files) in the root folder of the export.
![image](https://github.com/obsidianmd/obsidian-importer/assets/23269655/5325ba87-5b6c-4e5d-a92c-f3f9dce5cfab)

**Comment by AmusingMallard** [comment]
And just tested importing that export into Obsidian. Importer worked perfectly. The empty note that only contained the attached zip now just contains the file name of the zip file and there's an emtpy attachments folder at the root level.
![image](https://github.com/obsidianmd/obsidian-importer/assets/23269655/228a3bc9-ae0f-41b5-835f-1cf80f459ede)

Is it possible to also implement an error message about the zip file being skipped?

Another thing is that I get this error message about index.html in the root folder. I got that in my first import as well. Is that normal?
![image](https://github.com/obsidianmd/obsidian-importer/assets/23269655/4168310d-0f7d-42c6-afc5-be8a3beb46c6)
![image](https://github.com/obsidianmd/obsidian-importer/assets/23269655/d41491cf-a6f4-4481-bf4d-3f4fc4861360)

**Comment by joshuatazrein** [comment]
index.html should be skipped. It's just something Notion includes, but isn't a real page.
