### ISSUE TITLE
Importer not correctly handling Notion Teamspace update

### ISSUE THREAD

**Issue by pjbakker** [obsidianmd/obsidian-importer#79]
With Teamspaces everything in your export has an extra folder layer.

When importing an 'HTML export' the importer will only import 1 file with no actual data appearing after import.

To solve this manually:

* extract the zip file
* Compress all the folders in the extracted zip separately and import those (import work well on the teamspaces themselves)

Preferred solution: The Notion importer plugin correctly handles the additional teamspace layer that was introduced by Notion

**Comment by joshuatazrein** [comment]
In order to debug this I need a Teamspace export. Can you attach one to this issue if possible?

**Comment by pjbakker** [comment]
@joshuatazrein I didn't have time yet to create a custom Notion account export for debugging purposes for you.

The export has over a 1000 pages. When I import the ZIP returned from Notion export, I expect a full import, but I get this as a result:

<img width="550" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/1267780/afd1e856-ac36-46d0-9d4c-97116cc37665">

When I extract the ZIP I get this folder structure:

<img width="512" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/1267780/7c682c15-8b3e-467d-b9d6-507235d9b9c7">

And if I re-zip each of these folders:

<img width="521" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/1267780/00d55b0f-f225-47e5-8b93-e8bd939a70c7">

If I import those ZIP files individually, it works as expected. All my 1000+ pages are there. There are some failures but I'm not sure if that's always the case.

<img width="546" alt="image" src="https://github.com/obsidianmd/obsidian-importer/assets/1267780/7346d6a3-467d-476b-9435-147cd169c9ad">

**Comment by joshuatazrein** [comment]
Thanks for these screenshots. The issue seems to be that the `Export-` etc. file is somehow inside the `.zip` your are importing, which shouldn't be the case in any Notion export. Try importing the `Export` file directly and see if it works. I've never experienced an issue with Notion importing the root `Export` as an attachment—it might be because I'm on MacOS? Not sure.

**Comment by pjbakker** [comment]
W.r.t. the failed files, I cannot see the full names (they are abbreviated with '...').

I think that's caused because I import into a new folder, but attachments get 'imported' to the root, so the already exist as I now re-import the same pages to a subfolder I can delete.

**Comment by joshuatazrein** [comment]
Ok, sounds good.

**Comment by pjbakker** [comment]
Ok..

The Notion Desktop App export has this content:
```
unzip -l export-full.zip
Archive:  export-full.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
124067765  09-07-2023 07:36   Export-97a97faa-a05e-49f3-8149-0b4db9d587a0-Part-1.zip
---------                     -------
124067765                     1 file
```

Just checked. Same occurs by downloading from the Notion link.

So that might explain the issue. The zip contains another zip! Not sure why though.

**Comment by joshuatazrein** [comment]
Yes, that's probably what setting you have selected for Attachments.

**Comment by pjbakker** [comment]
Which 'Attachments' setting are you referring to? I don't see anything related to attachments in Notion Export or Obsidian Importer for Notion?

**Comment by pjbakker** [comment]
@kepano You closed this issue, but the file that is retrieved from Notion is a the HTML/folders in a ZIP in a ZIP.

Did you close it because Obsidian now handles ZIP in ZIP? Or did it get closed because the ZIP in ZIP cannot be reproduced by anyone else?

**Comment by pjbakker** [comment]
@joshuatazrein Did you see this question that stems from the answer you gave?

> Which 'Attachments' setting are you referring to? I don't see anything related to attachments in Notion Export or Obsidian Importer for Notion?

**Comment by joshuatazrein** [comment]
It’s in Obsidian’s general settings. Notion just follows whatever setting you have for the vault.

Sent with Spark
