### ISSUE TITLE
Does this plug-in(obsidian-importer) support the Chinese version Evernote(印象笔记)?

### ISSUE THREAD

**Issue by WrathGluttony** [obsidianmd/obsidian-importer#80]
①Does this plug-in(obsidian-importer) support the Chinese version(印象笔记)?
②The Chinese name of Evernote is "印象笔记"
Thanks.

**Comment by ericaxu** [comment]
Hi, I'm not familiar with the Chinese version. Could you give it a try? It wouldn't hurt.

**Comment by WrathGluttony** [comment]
Sorry,I'm not familiar with the Chinese version too.
