### ISSUE TITLE
Equations are not imported correctly from Notion

### ISSUE THREAD

**Issue by grintroy** [obsidianmd/obsidian-importer#81]
When importing from Notion:

- Equations are not enclosed in `$...$` or `$$...$$`
- Overall, equations are duplicated in a following way: [visual representation][actual LaTeX][visual representation again].

For example, take a look at the following equation (screenshot from Notion)

<img width="333" alt="Screenshot 2023-08-27 at 13 30 17" src="https://github.com/obsidianmd/obsidian-importer/assets/70978482/edbaea5b-ac1a-462f-a5cf-03450e368e9a">

It is imported as

```latex
f(t)≈12A0+∑n=1∞Ancos⁡(nω0t+θn)f(t) \approx {1\over2} A_0 + \sum_{n=1}^{\infty} A_n \cos(n \omega_0 t + \theta _n)f(t)≈21​A0​+n=1∑∞​An​cos(nω0​t+θn​)​​
```

Note that the Importer placed the actual LaTeX `f(t) \approx {1\over2} A_0 + \sum_{n=1}^{\infty} A_n \cos(n \omega_0 t + \theta _n)` in between the visual representation of the formula in plaintext `f(t)≈12A0+∑n=1∞Ancos⁡(nω0t+θn)`.

This happens to all formulas imported to Obsidian.

**Comment by wysstobi** [comment]
A possible approach could be to replace  all '.katex' elements with just the content of the corresponding `<annotation>` tag. This content could then be wrapped with `$` signs.
