### ISSUE TITLE
Notion bug squash bounty - $200

### ISSUE THREAD

**Issue by ericaxu** [obsidianmd/obsidian-importer#84]
## Bounty

See the [Contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md) for how to claim this bounty.

**Bounty:** $200 USD
**Timeframe:** 10 days

## Bugs

- [ ] https://github.com/obsidianmd/obsidian-importer/issues/83
- [ ] https://github.com/obsidianmd/obsidian-importer/issues/82
- [ ] https://github.com/obsidianmd/obsidian-importer/issues/81
- [ ] https://github.com/obsidianmd/obsidian-importer/issues/79
- [ ] https://github.com/obsidianmd/obsidian-importer/issues/76
- [ ] https://github.com/obsidianmd/obsidian-importer/issues/75

**Comment by joshuatazrein** [comment]
I'm on it!
