### ISSUE TITLE
Notion callouts are not handled properly

### ISSUE THREAD

**Issue by grintroy** [obsidianmd/obsidian-importer#92]
When importing from Notion, the callouts are not translated into [Obsidian callouts](https://help.obsidian.md/Editing+and+formatting/Callouts). Instead, just the icon and the text are imported.

For example, consider this callout (screenshot from Notion):

![Notion callout](https://github.com/obsidianmd/obsidian-importer/assets/70978482/85f755b8-e2be-4f3d-9501-c853c3eb77cd)

When imported to Obsidian, it is translated to

```
💡
    
PCIe can use multiple (up to 32) lanes per card reaching the max rate of 31.51 GB/s for v4.0.
```

Instead, it should be

```
> [!info]
> PCIe can use multiple (up to 32) lanes per card reaching the max rate of 31.51 GB/s for v4.0.
```

It should be unindented and might use a different
type identifier.

**Comment by kepano** [comment]
Closed via [1.5.5](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.5.5)
