### ISSUE TITLE
OneNote fails to import

### ISSUE THREAD

**Issue by jbins6499** [obsidianmd/obsidian-importer#93]
When I select OneNote as the import option then click sign in, it'll direct me to my microsoft sign in page on my browser. When I sign in it will ask me if I'm trying to import into Obsidian. I click yes. As soon as I do that, an error message pops up in Obsidian that says "Unexpected "Auth event. Please restart the auth process."

Importer will show my notebooks from my account. But when I hit import the progress bar shows up but it doesn't do anything. The folder is created that I designate as the import location but it's empty.

**Comment by pixelrazer** [comment]
i'm also having the same issue

**Comment by reemagit** [comment]
exactly same issue here

**Comment by cpittsjr** [comment]
I have the same issue. Mine was due to my account having 2-factor authentication on. After turning it off, I was able to connect.

**Comment by reemagit** [comment]
I just checked and I do not have 2FA activated on my account, but still get the issue.

**Comment by pixelrazer** [comment]
i just disabled 2FA and it didnt give me the "Auth event. Please restart the auth process" but the progress bar shows up but it doesn't do anything. The folder is created that I designate as the import location but it's empty.

**Comment by kepano** [comment]
Can you try updating the plugin to 1.3.1 and see if this issue is fixed?

**Comment by jbins6499** [comment]
> Can you try updating the plugin to 1.3.1 and see if this issue is fixed?

Still gives the Auth error, but the notebooks do import. However, I tried importing a single page and images imported all weird. There are three different images on the page in onenote and when I import it it just takes the first image and puts in the place of all  the other images. I also get a log error on the import process that says failed to import picture because it already exists.

**Comment by kepano** [comment]
> There are three different images on the page in onenote and when I import it it just takes the first image and puts in the place of all the other images. I also get a log error on the import process that says failed to import picture because it already exists.

Please open a separate issue with steps to reproduce — ideally a way to recreate this scenario on our side

**Comment by cpittsjr** [comment]
I just want to confirm that like @jbins6499, I still get a Auth error, but it still connects and imports.

**Comment by psterpe** [comment]
Would you consider reopening this? I can still reproduce it. Running Obsidian 1.4.13 on macOS Ventura 13.2.1 using v1.3.1 of the Importer. I always get that "Unexpected Auth Event." The importer does display a list of notebooks and their sections for me to check off. The import progress dialog says, "Starting OneNote import...," and also "1 remaining," and the Done button lights up. When I click Done, everything that appears to have imported is empty -- 0 files, 0 folders. I see no error messages. Once I got a single note correctly imported, but in that section of the notebook, there are 18 notes that should have imported.

<img width="557" alt="Obsidian_Import_dialog" src="https://github.com/obsidianmd/obsidian-importer/assets/5543626/689fa4d9-18cf-4457-b86f-ae84e64734e3">

**Comment by kepano** [comment]
@psterpe you can open a new issue but we need more specific steps to reproduce

**Comment by psterpe** [comment]
> @psterpe you can open a new issue but we need more specific steps to reproduce

I feared if I opened a new issue, it would be closed immediately as a duplicate of #93. It's the same issue, really. But I'll do that....

**Comment by ericaxu** [comment]
> > @psterpe you can open a new issue but we need more specific steps to reproduce
> 
> I feared if I opened a new issue, it would be closed immediately as a duplicate of #93. It's the same issue, really. But I'll do that....

Thank you for taking the time to do that!

**Comment by ingoratsdorf** [comment]
Looks like the importer can only import "personal" notebooks from a personal MS account. Business OIneNote does not seem to work - at least according to some other discussion : [https://forum.obsidian.md/t/new-to-obsidian-and-migrating-from-onenote/85499](https://forum.obsidian.md/t/new-to-obsidian-and-migrating-from-onenote/85499)

And it looks like it has not been fixed until today.
