### ISSUE TITLE
OneNote import duplicating images/not importing at all

### ISSUE THREAD

**Issue by jbins6499** [obsidianmd/obsidian-importer#95]
I'm noticing quite a few issues on my end with OneNote import.

- I make a notebook in OneNote and added a section. That section contains one note. That note has some text and three different images.
- I select OneNote in Importer and sign in via web browser. Obsidian says "Unexpected Auth event. Please restart the auth process." 
- I click Import and the progress bar shows. Two error messages pop up saying something like 
	- Cannot copy image002.png, file already exists.
	- Cannot copy image003. png, file already exists.
- I go to the import location and see the attachments folder and the converted page. The attachment folder only contains one image. I open up the note and that one image (image001.png) is now in the note three times, replacing the second and third images with the first.
- I decided to try to recreate this with a new note in OneNote. I create a new note in the same section and add some text and three images. I save and exit OneNote, go back to Obsidian Importer and sign in browser again. I click import and now it doesn't even want to import at all. No progress. 
- I then try to make a new section in OneNote and move that test note to that section. Save and exit OneNote. Sign in on Obsidian Importer and see thay the new section pops up. Click import. Same thing, no progress. it creates a folder location for each section in my vault but no files are imported.
- I go back to OneNote. Delete the second section and test note and get it back to where it was with the original note in one section. I then try to import the *original* note with the three images and now we're back to the issue of only one image importing and replacing the two other instances of images.

**Comment by ashemedai** [comment]
I address at least part of your report, the repeated images, in #102 - but some of your other points don't seem to be related to what I reported.

**Comment by ashemedai** [comment]
@kepano @p3rid0t Unfortunately this is not quite working as it should with the latest importer update, this is what happens per page that is now imported via OneNote:

![image](https://github.com/obsidianmd/obsidian-importer/assets/610865/2dfba4c6-5809-4c31-be4c-9d04411c5f39)

That "A complete Mercurial branching strategy.md" directory corresponding to the Page of the same name in OneNote has only 6 images. But the resulting import has 124 files created. That "A succesful Git branching model considered harmful.md" Page has 6 as well, but the directory after import has 113 files created.
